##########################################
## sonoffMini1 http://192.168.0./
## ??
##
- platform: mqtt
  name: "Luz Despacho"
  state_topic: "stat/sonoffMini1/POWER"
  command_topic: "cmnd/sonoffMini1/POWER"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  icon: mdi:power-socket-eu