##########################################
## sonoffMini10 http://192.168.0./
## ??
##
- platform: mqtt
  name: "mini10"
  state_topic: "stat/sonoffMini10/POWER"
  command_topic: "cmnd/sonoffMini10/POWER"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  icon: mdi:power-socket-eu