##########################################
## sonoffMini5 http://192.168.0./
## ??
##
- platform: mqtt
  name: "sonoffMini5"
  state_topic: "stat/sonoffMini5/POWER"
  command_topic: "cmnd/sonoffMini5/POWER"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  icon: mdi:power-socket-eu