##########################################
## BlitzWolf SHP2 (2.3) http://192.168.0.160
## BliTZW0lF_1 
##

- platform: mqtt
  name: "BliTZW0lF_1"
  state_topic: "stat/BliTZW0lF_1/POWER"
  command_topic: "cmnd/BliTZW0lF_1/POWER"
  availability_topic: "tele/BliTZW0lF_1/LWT"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  icon: mdi:speedometer
  
##########################################
## BlitzWolf SHP2 (2.3) http://192.168.0.161
## BliTZW0lF_2 
##

- platform: mqtt
  name: "BliTZW0lF_2"
  state_topic: "stat/BliTZW0lF_2/POWER"
  command_topic: "cmnd/BliTZW0lF_2/POWER"
  availability_topic: "tele/BliTZW0lF_2/LWT"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  icon: mdi:speedometer

##########################################
## BlitzWolf SHP2 (normal) http://192.168.0.162
## BliTZW0lF_3 
##

- platform: mqtt
  name: "BliTZW0lF_3"
  state_topic: "stat/BliTZW0lF_3/POWER"
  command_topic: "cmnd/BliTZW0lF_3/POWER"
  availability_topic: "tele/BliTZW0lF_3/LWT"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  icon: mdi:speedometer

##########################################
## BlitzWolf SHP2 (normal) http://192.168.0.163
## BliTZW0lF_4
##

- platform: mqtt
  name: "BliTZW0lF_4"
  state_topic: "stat/BliTZW0lF_4/POWER"
  command_topic: "cmnd/BliTZW0lF_4/POWER"
  availability_topic: "tele/BliTZW0lF_4/LWT"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  icon: mdi:speedometer
  
###########################################
### BlitzWolf SHP2 (espurna) http://192.168.0.163
### BliTZW0lF_4
###
#- platform: mqtt
#  name: BliTzW0lf4
#  state_topic: BliTzW0lf4/relay/0
#  command_topic: BliTzW0lf4/relay/0/set
#  payload_on: 1
#  payload_off: 0
#  availability_topic: BliTzW0lf4/status
#  payload_available: 1
#  payload_not_available: 0
    
##########################################
## Sonoff s26 http://192.168.0.151/
## Waterheater
##
- platform: mqtt
  name: "sonoffAmbiCorredor"
  #friendly_name: "Ambi Corredor"
  state_topic: "stat/sonoffS26_1/POWER"
  command_topic: "cmnd/sonoffS26_1/POWER"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  icon: mdi:power-socket-eu
  
##########################################
## Sonoff s26 http://192.168.0.152/
## TV set
##
- platform: mqtt
  name: "sonoffTVset"
  #friendly_name: "TV set"
  state_topic: "stat/sonoffS26_2/POWER"
  command_topic: "cmnd/sonoffS26_2/POWER"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  icon: mdi:power-socket-eu
  
##########################################
## Sonoff s26 http://192.168.0.153/
## TV set
##
- platform: mqtt
  name: "sonoffAmbiBany"
  #friendly_name: "Ambi Bany"
  state_topic: "stat/sonoffS26_3/POWER"
  command_topic: "cmnd/sonoffS26_3/POWER"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  icon: mdi:power-socket-eu
  
    ##########################################
## Sonoff s26 http://192.168.0.154/
## proves
##
- platform: mqtt
  name: "sonoffBasic"
  #friendly_name: "Proves"
  state_topic: "stat/sonoffBasic_1/POWER"
  command_topic: "cmnd/sonoffBasic_1/POWER"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  icon: mdi:power-socket-eu
  
##########################################
## Broadlink RMmini3 192.168.0.168
## Ir Switch
##
- platform: broadlink
  host: !secret rm_mini_3_menjador_ip
  mac: !secret rm_mini_3_menjador_mac
  timeout: 15
  type: rm_mini
  friendly_name: 'RMmini3 menjador'
#  switches:
#    aire_menjador:
#      friendly_name: "Aire Menjador On/Off"
#      command_off: 'JgAWAm44DioNDw0PDQ4NDw0PDQ8NDg4ODQ8NDw0ODioNDw0ODg4NDw0PDQ8NDg0PDQ8NDw0ODg4NDw0PDQ4ODg0PDSsNDg0rDSoNKw0qDSsNKg4ODSsNKg0rDSoNKw0qDioNKg4qDQ8NDg4ODQ8NDw0PDQ4NDw0PDQ8NKg0rDQ4ODg0rDSoNKw0qDQ8NDw0qDioNDw0ODg4NKw0PDQ4NKw0PDQ4NKw0qDg4NKw0qDQ8NKw0qDQ8NKg0rDQ8NDg0rDQ8NDg4ODQ8NDw0qDSsNDw0qDSsNKg0PDQ8NDg4ODSsNKg0rDQ8NKg0rDSoNKw0PDQ4NDw0rDQ4NDw0PDQ8NDg0PDQ8NDw0qDSsNKg0rDSoNKw0qDSsNDw0ODg4NDw0PDQ4ODg0PDSoOKg0rDSoNKw0qDSsNKg0PDQ8NDw0ODQ8NDw0PDQ4NKw0qDioNKg4qDSsNKg0rDQ4NDw0PDQ8NDg4ODQ8NDw0qDSsNKg0rDSoNKw0qDioNDw0ODg4NDw0PDQ4ODg0PDSsNKg0rDSoNKw0qDSsNKg0rDQ8NDg0PDQ8NDw0qDQ8NDw0qDSsNKg0rDSoNDw0rDSoNDw0PDQ4ODg0PDSsNKg0PDSoNKw0qDioNKg4ODQ8NDw0PDQ4NDw0rDSoNDw0PDSoNKw0qDSsNDw0ODSsNKg0rDQ8NDg4ODSsNDg4ODQ8NDw0qDSsNKg0PDSsNKg0rDQANBQAA'
#      command_on:  'JgAWAm84DSsNDg4ODQ8NDw0PDQ4NDw0PDQ8NDg0PDSsNDg4ODQ8NDw0ODg4NDw0PDQ8NDg0PDQ8NDw0ODQ8NDw0PDSoNDw0qDioNKw0qDSsNKg0PDSoOKg0qDioNKw0qDSsNKg0rDQ4ODg0PDQ8NDg4ODQ8NDw0ODg4NKw0qDQ8NDw0qDioNKg4qDQ8NDw0qDSsNDg0PDQ8NKg4ODQ8NKg4ODQ8NKw0qDQ8NKg0rDQ8NKg0rDQ4OKg0rDQ4NDw0rDQ4NDw0PDQ8NDg4qDSoODg0rDSsMKw0PDQ4NDw0PDSoOKg0qDg4NKw0qDSsNKg0PDQ8NDw0qDQ8NDw0PDQ4NDw0PDQ8NDg0rDSoNKw0qDioNKw0qDSsNDg0PDQ8NDw0ODQ8NDw0PDSoNKw0qDSsNKg0rDSoNKw0PDQ4ODg0PDQ8NDw0ODQ8NKw0qDSsNKg0rDSoNKw0qDQ8NDw0PDQ4NDw0PDQ8NDg4qDSoOKg0qDioNKw0qDSsNDg4ODQ8NDw0ODg4NDw0PDSoNKw0qDSsNKg4qDSoOKg0rDQ4NDw0PDQ8NDg0rDQ8NDg4qDSoOKg0rDSoNDw0qDSsNDw0ODg4NKw0ODioNKw0ODSsNKg0rDQ8NKg0PDQ8NDg4ODQ8NDw0qDSsNDw0ODSsNKg4qDSoODg0PDSsNKg0rDQ4NDw0PDSoODg0PDQ8NDg4qDSsNKg0PDSsMKw0qDgANBQAA'
#      
##########################################
## Broadlink RMmini3 192.168.0.169
## Ir Switch
##
- platform: broadlink
  host: !secret rm_mini_3_despatx_ip
  mac: !secret rm_mini_3_despatx_mac
#  timeout: 15
#  type: rm_mini
#  friendly_name: 'RMmini3 despatx'
#  switches:
#    aire_despatx:
#      friendly_name: "Aire Despatx On/Off"
#      command_off: 'JgAWAm44DioNDw0PDQ4NDw0PDQ8NDg4ODQ8NDw0ODioNDw0ODg4NDw0PDQ8NDg0PDQ8NDw0ODg4NDw0PDQ4ODg0PDSsNDg0rDSoNKw0qDSsNKg4ODSsNKg0rDSoNKw0qDioNKg4qDQ8NDg4ODQ8NDw0PDQ4NDw0PDQ8NKg0rDQ4ODg0rDSoNKw0qDQ8NDw0qDioNDw0ODg4NKw0PDQ4NKw0PDQ4NKw0qDg4NKw0qDQ8NKw0qDQ8NKg0rDQ8NDg0rDQ8NDg4ODQ8NDw0qDSsNDw0qDSsNKg0PDQ8NDg4ODSsNKg0rDQ8NKg0rDSoNKw0PDQ4NDw0rDQ4NDw0PDQ8NDg0PDQ8NDw0qDSsNKg0rDSoNKw0qDSsNDw0ODg4NDw0PDQ4ODg0PDSoOKg0rDSoNKw0qDSsNKg0PDQ8NDw0ODQ8NDw0PDQ4NKw0qDioNKg4qDSsNKg0rDQ4NDw0PDQ8NDg4ODQ8NDw0qDSsNKg0rDSoNKw0qDioNDw0ODg4NDw0PDQ4ODg0PDSsNKg0rDSoNKw0qDSsNKg0rDQ8NDg0PDQ8NDw0qDQ8NDw0qDSsNKg0rDSoNDw0rDSoNDw0PDQ4ODg0PDSsNKg0PDSoNKw0qDioNKg4ODQ8NDw0PDQ4NDw0rDSoNDw0PDSoNKw0qDSsNDw0ODSsNKg0rDQ8NDg4ODSsNDg4ODQ8NDw0qDSsNKg0PDSsNKg0rDQANBQAA'
#      command_on: 'JgAWAm84DSsNDg4ODQ8NDw0PDQ4NDw0PDQ8NDg0PDSsNDg4ODQ8NDw0ODg4NDw0PDQ8NDg0PDQ8NDw0ODQ8NDw0PDSoNDw0qDioNKw0qDSsNKg0PDSoOKg0qDioNKw0qDSsNKg0rDQ4ODg0PDQ8NDg4ODQ8NDw0ODg4NKw0qDQ8NDw0qDioNKg4qDQ8NDw0qDSsNDg0PDQ8NKg4ODQ8NKg4ODQ8NKw0qDQ8NKg0rDQ8NKg0rDQ4OKg0rDQ4NDw0rDQ4NDw0PDQ8NDg4qDSoODg0rDSsMKw0PDQ4NDw0PDSoOKg0qDg4NKw0qDSsNKg0PDQ8NDw0qDQ8NDw0PDQ4NDw0PDQ8NDg0rDSoNKw0qDioNKw0qDSsNDg0PDQ8NDw0ODQ8NDw0PDSoNKw0qDSsNKg0rDSoNKw0PDQ4ODg0PDQ8NDw0ODQ8NKw0qDSsNKg0rDSoNKw0qDQ8NDw0PDQ4NDw0PDQ8NDg4qDSoOKg0qDioNKw0qDSsNDg4ODQ8NDw0ODg4NDw0PDSoNKw0qDSsNKg4qDSoOKg0rDQ4NDw0PDQ8NDg0rDQ8NDg4qDSoOKg0rDSoNDw0qDSsNDw0ODg4NKw0ODioNKw0ODSsNKg0rDQ8NKg0PDQ8NDg4ODQ8NDw0qDSsNDw0ODSsNKg4qDSoODg0PDSsNKg0rDQ4NDw0PDSoODg0PDQ8NDg4qDSsNKg0PDSsMKw0qDgANBQAA'
#    musica_despatx:
#      friendly_name: "Technics Musica On/Off"
#      command_on:  'JgDMAHU3EA4OKw8ODRANDw0QDRANDw0RDRANDw0QDg8NLA8ODQ8OEA0PDQ8ODw4QDSwNEA0sDRENDw0sDw4NEA0PDg8NEA0tDQ8OLA0sDS0OKw4PDg8NLA4PDQ8OLA0tDQ8ODxApDgAJnHM5Dg8PKw4ODw4PDg8ODw4ODg8ODw4ODg8ODw4PKxAMDw4PDw4ODw4PDg4ODyoPDg8qDw8PDg4rDg8ODw8ODg4PDg8qDw4PKg8qDywOKw4PDg4PKw8ODw4PKg4rDw4PDg4rDgANBQAAAAAAAAAAAAAAAA==='
#      command_off: 'JgBmAHU3EA4OKxANDg8NDw4PDg8NDw4QDQ8ODw4PDRAOKxANDg8ODg4PDg8NDw4QDisQDQ4rEA4NDw4sDw0ODw4PDQ8ODw4sEA0NLA8qECoQKg8NDg8OKxANDg8NLA8rEA0ODg4sEAANBQAA==='          
#    musica_despatxplayCD:
#      friendly_name: "Technics Musica PlayCD"
#      command_on: 'JgAyAHNzHB0dHB1WHVUeHB0cHVUdVh0cHhwdHB1WHFYdHB4cHVUdVh0cHR0dVR1WHVUdAA0FAAAAAAAA==='
#      command_off: 'JgAyAHNzHB0dHB1WHVUeHB0cHVUdVh0cHhwdHB1WHFYdHB4cHVUdVh0cHR0dVR1WHVUdAA0FAAAAAAAA==='
#    musica_despatxpauseCD:
#      friendly_name: "Technics Musica PauseCD"
#      command_on: 'JgBkAHNyHhsfGx1VHFceGx0cHlUcHR5VHRweGx1WHFccHRwdHVYcVh0dHFYcHhtXHlUcAASsc3IfGxwdHFceVB4cHRwcVhweHVUeHBwdHFYdVh4bHB4eVB5VHhscVx0cHlQeVR4ADQUAAAAA==='
#      command_off: 'JgBkAHNyHhsfGx1VHFceGx0cHlUcHR5VHRweGx1WHFccHRwdHVYcVh0dHFYcHhtXHlUcAASsc3IfGxwdHFceVB4cHRwcVhweHVUeHBwdHFYdVh4bHB4eVB5VHhscVx0cHlQeVR4ADQUAAAAA==='
#    musica_despatxstopCD:
#      friendly_name: "Technics Musica StopCD"
#      command_on:  'JgDMAHM5Dw8OKw8ODg4PDg8ODg4PDg8ODw4PDg4ODw8PKg8ODw0PDg8ODw0PDg8PDisPDg4rDw4PDg8qDw4PDg4ODw4PDg4PDw4ODg8ODw8ODg8qDysODg8ODyoPDg8PDisOKw8ODwAJnHM5Dw0PKw4ODw4PDw4ODw4PDQ8PDw4ODg8ODw4OKw8ODg4PDw4ODw4PDg4PDyoPDg8qDw4PDg4rDg8ODw8ODw4ODg8PDg4PDg8ODg4PDg8qDyoPDw8ODisODw4PDyoPKw4ODwANBQAAAAAAAAAAAAAAAA==='
#      command_off:  'JgDMAHM5Dw8OKw8ODg4PDg8ODg4PDg8ODw4PDg4ODw8PKg8ODw0PDg8ODw0PDg8PDisPDg4rDw4PDg8qDw4PDg4ODw4PDg4PDw4ODg8ODw8ODg8qDysODg8ODyoPDg8PDisOKw8ODwAJnHM5Dw0PKw4ODw4PDw4ODw4PDQ8PDw4ODg8ODw4OKw8ODg4PDw4ODw4PDg4PDyoPDg8qDw4PDg4rDg8ODw8ODw4ODg8PDg4PDg8ODg4PDg8qDyoPDw8ODisODw4PDyoPKw4ODwANBQAAAAAAAAAAAAAAAA==='
#    musica_despatxprevCD:
#      friendly_name: "Technics Musica PrevCD"
#      command_on: 'JgDMAHM5Dw4OKw8ODg4PDw8ODg4PDg8ODw4PDg4ODw4PKg8ODw0PDw8ODg4PDg8PDisODg8rDw0PDg8ODisOEA4ODw4PDQ8PDyoPDg8qDw4PDg4ODw4PDg8rDg4PDg8ODysPDQ8rDgAJm3M5Dw4PKw4ODw4PDg4ODw4PDg4PDw4PDQ8ODw8OKw4PDg4PDg8ODg4PDg8ODysODg8qDw8PDg8NDysODg8ODw4ODg8PDyoPDg8qDw8ODg8ODw4ODg8qDw4PDg8ODysODg8qDwANBQAAAAAAAAAAAAAAAA==='
#      command_off: 'JgDMAHM5Dw4OKw8ODg4PDw8ODg4PDg8ODw4PDg4ODw4PKg8ODw0PDw8ODg4PDg8PDisODg8rDw0PDg8ODisOEA4ODw4PDQ8PDyoPDg8qDw4PDg4ODw4PDg8rDg4PDg8ODysPDQ8rDgAJm3M5Dw4PKw4ODw4PDg4ODw4PDg4PDw4PDQ8ODw8OKw4PDg4PDg8ODg4PDg8ODysODg8qDw8PDg8NDysODg8ODw4ODg8PDyoPDg8qDw8ODg8ODw4ODg8qDw4PDg8ODysODg8qDwANBQAAAAAAAAAAAAAAAA==='
#    musica_despatxnextCD:
#      friendly_name: "Technics Musica NextCD"
#      command_on: 'JgDMAHM5Dw4OKw8ODg4PDw8ODg4PDg8ODw4PDg4ODw4PKg8ODw0PDw8ODg4PDg8PDisODg8rDw0PDg8ODisOEA4ODw4PDQ8PDyoPDg8qDw4PDg4ODw4PDg8rDg4PDg8ODysPDQ8rDgAJm3M5Dw4PKw4ODw4PDg4ODw4PDg4PDw4PDQ8ODw8OKw4PDg4PDg8ODg4PDg8ODysODg8qDw8PDg8NDysODg8ODw4ODg8PDyoPDg8qDw8ODg8ODw4ODg8qDw4PDg8ODysODg8qDwANBQAAAAAAAAAAAAAAAA==='
#      command_off: 'JgDMAHM5Dw4OKw8ODg4PDw8ODg4PDg8ODw4PDg4ODw4PKg8ODw0PDw8ODg4PDg8PDisODg8rDw0PDg8ODisOEA4ODw4PDQ8PDyoPDg8qDw4PDg4ODw4PDg8rDg4PDg8ODysPDQ8rDgAJm3M5Dw4PKw4ODw4PDg4ODw4PDg4PDw4PDQ8ODw8OKw4PDg4PDg8ODg4PDg8ODysODg8qDw8PDg8NDysODg8ODw4ODg8PDyoPDg8qDw8ODg8ODw4ODg8qDw4PDg8ODysODg8qDwANBQAAAAAAAAAAAAAAAA==='
 
- platform: mqtt
  name: "Lolin5 relay"  
  state_topic: "dmp/lolin5"  
  command_topic: "dmp/lolin5/relay"
  value_template: '{{ value_json.relay }}'
  qos: 2