# ##########################################
# ## BlitzWolf SHP2 (2.3) http://192.168.0.160
# ## BliTZW0lF_1 
# ##

# - platform: mqtt
#   name: "BliTZW0lF_1"
#   state_topic: "stat/BliTZW0lF_1/POWER"
#   command_topic: "cmnd/BliTZW0lF_1/POWER"
#   availability_topic: "tele/BliTZW0lF_1/LWT"
#   qos: 2
#   payload_on: "ON"
#   payload_off: "OFF"
#   payload_available: "Online"
#   payload_not_available: "Offline"
#   optimistic: false
#   icon: mdi:speedometer
  
##########################################
## Sonoff s26 http://192.168.0.151/
## AmbiCorredor
##
- platform: mqtt
  name: "sonoffAmbiCorredor"
  #friendly_name: "Ambi Corredor"
  state_topic: "stat/sonoffS26_1/POWER"
  command_topic: "cmnd/sonoffS26_1/POWER"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  icon: mdi:power-socket-eu
  
##########################################
## Sonoff s26 http://192.168.0.152/
## Lampara Menjador
##
- platform: mqtt
  name: "sonoffS26_2"
  state_topic: "stat/sonoffS26_2/POWER"
  command_topic: "cmnd/sonoffS26_2/POWER"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  icon: mdi:power-socket-eu
  
##########################################
## Sonoff s26 http://192.168.0.153/
## AmbiBany
##
- platform: mqtt
  name: "sonoffAmbiBany"
  state_topic: "stat/sonoffS26_3/POWER"
  command_topic: "cmnd/sonoffS26_3/POWER"
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  icon: mdi:power-socket-eu

#   ##########################################
# ## Broadlink RMmini3 192.168.0.168
# ## Ir Switch
# ##
##- platform: broadlink
#  #host: !secret rm_mini_3_menjador_ip
#  host: 192.168.0.168
#  #mac: !secret rm_mini_3_menjador_mac
##  mac: 78:0F:77:D6:3A:FC
#   type: rm_mini
#   friendly_name: 'RMmini3 menjador'
#   switches:
#     aire_menjador:
#       friendly_name: "Aire Menjador On/Off"
#       command_off: 'JgAWAm44DioNDw0PDQ4NDw0PDQ8NDg4ODQ8NDw0ODioNDw0ODg4NDw0PDQ8NDg0PDQ8NDw0ODg4NDw0PDQ4ODg0PDSsNDg0rDSoNKw0qDSsNKg4ODSsNKg0rDSoNKw0qDioNKg4qDQ8NDg4ODQ8NDw0PDQ4NDw0PDQ8NKg0rDQ4ODg0rDSoNKw0qDQ8NDw0qDioNDw0ODg4NKw0PDQ4NKw0PDQ4NKw0qDg4NKw0qDQ8NKw0qDQ8NKg0rDQ8NDg0rDQ8NDg4ODQ8NDw0qDSsNDw0qDSsNKg0PDQ8NDg4ODSsNKg0rDQ8NKg0rDSoNKw0PDQ4NDw0rDQ4NDw0PDQ8NDg0PDQ8NDw0qDSsNKg0rDSoNKw0qDSsNDw0ODg4NDw0PDQ4ODg0PDSoOKg0rDSoNKw0qDSsNKg0PDQ8NDw0ODQ8NDw0PDQ4NKw0qDioNKg4qDSsNKg0rDQ4NDw0PDQ8NDg4ODQ8NDw0qDSsNKg0rDSoNKw0qDioNDw0ODg4NDw0PDQ4ODg0PDSsNKg0rDSoNKw0qDSsNKg0rDQ8NDg0PDQ8NDw0qDQ8NDw0qDSsNKg0rDSoNDw0rDSoNDw0PDQ4ODg0PDSsNKg0PDSoNKw0qDioNKg4ODQ8NDw0PDQ4NDw0rDSoNDw0PDSoNKw0qDSsNDw0ODSsNKg0rDQ8NDg4ODSsNDg4ODQ8NDw0qDSsNKg0PDSsNKg0rDQANBQAA'
#       command_on:  'JgAWAm84DSsNDg4ODQ8NDw0PDQ4NDw0PDQ8NDg0PDSsNDg4ODQ8NDw0ODg4NDw0PDQ8NDg0PDQ8NDw0ODQ8NDw0PDSoNDw0qDioNKw0qDSsNKg0PDSoOKg0qDioNKw0qDSsNKg0rDQ4ODg0PDQ8NDg4ODQ8NDw0ODg4NKw0qDQ8NDw0qDioNKg4qDQ8NDw0qDSsNDg0PDQ8NKg4ODQ8NKg4ODQ8NKw0qDQ8NKg0rDQ8NKg0rDQ4OKg0rDQ4NDw0rDQ4NDw0PDQ8NDg4qDSoODg0rDSsMKw0PDQ4NDw0PDSoOKg0qDg4NKw0qDSsNKg0PDQ8NDw0qDQ8NDw0PDQ4NDw0PDQ8NDg0rDSoNKw0qDioNKw0qDSsNDg0PDQ8NDw0ODQ8NDw0PDSoNKw0qDSsNKg0rDSoNKw0PDQ4ODg0PDQ8NDw0ODQ8NKw0qDSsNKg0rDSoNKw0qDQ8NDw0PDQ4NDw0PDQ8NDg4qDSoOKg0qDioNKw0qDSsNDg4ODQ8NDw0ODg4NDw0PDSoNKw0qDSsNKg4qDSoOKg0rDQ4NDw0PDQ8NDg0rDQ8NDg4qDSoOKg0rDSoNDw0qDSsNDw0ODg4NKw0ODioNKw0ODSsNKg0rDQ8NKg0PDQ8NDg4ODQ8NDw0qDSsNDw0ODSsNKg4qDSoODg0PDSsNKg0rDQ4NDw0PDSoODg0PDQ8NDg4qDSsNKg0PDSsMKw0qDgANBQAA'
    
# ##########################################
# ## Broadlink RMmini3 192.168.0.169
# ## Ir Switch
# ##
##- platform: broadlink
#  host: !secret rm_mini_3_despatx_ip
##  mac: !secret rm_mini_3_despatx_mac
#   type: rm_mini
#   friendly_name: 'RMmini3 despatx'
#   switches:
#     aire_despatx:
#       friendly_name: "Aire Despatx On/Off"
#       command_off: 'JgAWAm44DioNDw0PDQ4NDw0PDQ8NDg4ODQ8NDw0ODioNDw0ODg4NDw0PDQ8NDg0PDQ8NDw0ODg4NDw0PDQ4ODg0PDSsNDg0rDSoNKw0qDSsNKg4ODSsNKg0rDSoNKw0qDioNKg4qDQ8NDg4ODQ8NDw0PDQ4NDw0PDQ8NKg0rDQ4ODg0rDSoNKw0qDQ8NDw0qDioNDw0ODg4NKw0PDQ4NKw0PDQ4NKw0qDg4NKw0qDQ8NKw0qDQ8NKg0rDQ8NDg0rDQ8NDg4ODQ8NDw0qDSsNDw0qDSsNKg0PDQ8NDg4ODSsNKg0rDQ8NKg0rDSoNKw0PDQ4NDw0rDQ4NDw0PDQ8NDg0PDQ8NDw0qDSsNKg0rDSoNKw0qDSsNDw0ODg4NDw0PDQ4ODg0PDSoOKg0rDSoNKw0qDSsNKg0PDQ8NDw0ODQ8NDw0PDQ4NKw0qDioNKg4qDSsNKg0rDQ4NDw0PDQ8NDg4ODQ8NDw0qDSsNKg0rDSoNKw0qDioNDw0ODg4NDw0PDQ4ODg0PDSsNKg0rDSoNKw0qDSsNKg0rDQ8NDg0PDQ8NDw0qDQ8NDw0qDSsNKg0rDSoNDw0rDSoNDw0PDQ4ODg0PDSsNKg0PDSoNKw0qDioNKg4ODQ8NDw0PDQ4NDw0rDSoNDw0PDSoNKw0qDSsNDw0ODSsNKg0rDQ8NDg4ODSsNDg4ODQ8NDw0qDSsNKg0PDSsNKg0rDQANBQAA'
#       command_on:  'JgAWAm84DSsNDg4ODQ8NDw0PDQ4NDw0PDQ8NDg0PDSsNDg4ODQ8NDw0ODg4NDw0PDQ8NDg0PDQ8NDw0ODQ8NDw0PDSoNDw0qDioNKw0qDSsNKg0PDSoOKg0qDioNKw0qDSsNKg0rDQ4ODg0PDQ8NDg4ODQ8NDw0ODg4NKw0qDQ8NDw0qDioNKg4qDQ8NDw0qDSsNDg0PDQ8NKg4ODQ8NKg4ODQ8NKw0qDQ8NKg0rDQ8NKg0rDQ4OKg0rDQ4NDw0rDQ4NDw0PDQ8NDg4qDSoODg0rDSsMKw0PDQ4NDw0PDSoOKg0qDg4NKw0qDSsNKg0PDQ8NDw0qDQ8NDw0PDQ4NDw0PDQ8NDg0rDSoNKw0qDioNKw0qDSsNDg0PDQ8NDw0ODQ8NDw0PDSoNKw0qDSsNKg0rDSoNKw0PDQ4ODg0PDQ8NDw0ODQ8NKw0qDSsNKg0rDSoNKw0qDQ8NDw0PDQ4NDw0PDQ8NDg4qDSoOKg0qDioNKw0qDSsNDg4ODQ8NDw0ODg4NDw0PDSoNKw0qDSsNKg4qDSoOKg0rDQ4NDw0PDQ8NDg0rDQ8NDg4qDSoOKg0rDSoNDw0qDSsNDw0ODg4NKw0ODioNKw0ODSsNKg0rDQ8NKg0PDQ8NDg4ODQ8NDw0qDSsNDw0ODSsNKg4qDSoODg0PDSsNKg0rDQ4NDw0PDSoODg0PDQ8NDg4qDSsNKg0PDSsMKw0qDgANBQAA'
#     musica_despatx:
#       friendly_name: "Technics Musica On/Off"
#       command_on:  'JgDMAHU3EA4OKw8ODRANDw0QDRANDw0RDRANDw0QDg8NLA8ODQ8OEA0PDQ8ODw4QDSwNEA0sDRENDw0sDw4NEA0PDg8NEA0tDQ8OLA0sDS0OKw4PDg8NLA4PDQ8OLA0tDQ8ODxApDgAJnHM5Dg8PKw4ODw4PDg8ODw4ODg8ODw4ODg8ODw4PKxAMDw4PDw4ODw4PDg4ODyoPDg8qDw8PDg4rDg8ODw8ODg4PDg8qDw4PKg8qDywOKw4PDg4PKw8ODw4PKg4rDw4PDg4rDgANBQAAAAAAAAAAAAAAAA==='
#       command_off: 'JgBmAHU3EA4OKxANDg8NDw4PDg8NDw4QDQ8ODw4PDRAOKxANDg8ODg4PDg8NDw4QDisQDQ4rEA4NDw4sDw0ODw4PDQ8ODw4sEA0NLA8qECoQKg8NDg8OKxANDg8NLA8rEA0ODg4sEAANBQAA==='          