##########################################
## INLINE_KEYBOARD - TCB_light_dormitorio_on
##
- alias: 'TCB_light_dormitorio_on'
  id: tcb_light_dormitorio_on
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_light_dormitorio_on'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching Dormitorio light on'
    - action: switch.turn_on
      data:
        entity_id:
          - switch.luz_dormitorio
    - delay: 00:00:01
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_lights_menu_buttons.btn