##########################################
## INLINE_KEYBOARD - TCB_lights_menu
##
- alias: 'TCB_lights_menu'
  id: tcb_lights_menu
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_lights_menu'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Lights menu selected'
    - action: telegram_bot.edit_message
      data:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        message: "\U0001f4a1 ***Lights*** \U0001f4a1"
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_lights_menu_buttons.btn

