##########################################
## INLINE_KEYBOARD - TCB_lights_menu
##
- alias: 'TCB_lights_menu'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_lights_menu'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Lights menu selected'
    - service: telegram_bot.edit_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        message: "\U0001f4a1 ***Lights*** \U0001f4a1"
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_lights_menu_buttons.btn

