##########################################
## INLINE_KEYBOARD - TCB_light_tvlamp_on
##
- alias: 'TCB_light_tvlamp_on'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_light_tvlamp_on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.sonoffs26_2
    - delay: 00:00:01
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching TVLamp light on'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_lights_menu_buttons.btn