- alias: 'Shutter LED toggle Dinner'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_shutter_toggle_led_dinner'
  action:
    - service: light.toggle
      data:
        entity_id: light.shutter_dinner_button_led
    - delay: 00:00:01
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'LED Dinner toggled'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_shutter_menu_buttons.btn
