##########################################
## INLINE_KEYBOARD - TCB_shutter_close_all
##
- alias: 'TCB_shutter_close_all'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_shutter_close_all'
  action:
    - service: cover.close_cover
      target:
        entity_id:
          - cover.shutter_office
          - cover.shutter_dinner
          - cover.shutter_sleep
          - cover.shutter_room
    - delay: 00:00:30
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching shutters to close'
    - service: telegram_bot.delete_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'