##########################################
## INLINE_KEYBOARD - TCB_shutter_label
##
- alias: 'TCB_shutter_label'
  id: tcb_shutter_label
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_shutter_label'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Shutter menu'