##########################################
## INLINE_KEYBOARD - TCB_shutter_close
##
- alias: 'TCB_shutter_close'
  id: tcb_shutter_close
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_shutter_close'
  actions:
    # - service: input_number.set_value
    #   data_template:
    #     entity_id: input_number.window_set_position
    #     value: 1
    # - delay: 00:00:01
    # - service: input_number.set_value
    #   data_template:
    #     entity_id: input_number.window_set_position
    #     value: 0
    - action: cover.close_cover
      target:
        entity_id: cover.shutter_office
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching Shutter to close'
    - delay: 00:00:30
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_shutter_menu_buttons.btn                 