##########################################
## INLINE_KEYBOARD - TCB_shutter_dinner_half
##
- alias: 'TCB_shutter_dinner_half'
  id: tcb_shutter_dinner_half
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_shutter_dinner_half'
  actions:
    - action: cover.set_cover_position
      target:
        entity_id: cover.shutter_dinner
      data:
        position: 70
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching Dinner Shutter to half open'
    - delay: 00:00:30
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_shutter_menu_buttons.btn