##########################################
## INLINE_KEYBOARD - TCB_shutter_open
##
- alias: 'TCB_shutter_open'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_shutter_open'
  action:
    # - service: input_number.set_value
    #   data_template:
    #     entity_id: input_number.window_set_position
    #     value: 99
    # - delay: 00:00:01            
    # - service: input_number.set_value
    #   data_template:
    #     entity_id: input_number.window_set_position
    #     value: 100
    - service: cover.open_cover
      target:
        entity_id: cover.shutter_office
    - delay: 00:00:30
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching Shutter to open'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_shutter_menu_buttons.btn                 