##########################################
## INLINE_KEYBOARD - TCB_shutter_room_open
##
- alias: 'TCB_shutter_room_open'
  id: tcb_shutter_room_open
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_shutter_room_open'
  actions:
    - action: cover.open_cover
      target:
        entity_id: cover.shutter_room
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching Room Shutter to open'
    - delay: 00:00:30
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_shutter_menu_buttons.btn