##########################################
## INLINE_KEYBOARD - TCB_shutter_half
##
- alias: 'TCB_shutter_half'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_shutter_half'
  action:
    # - service: input_number.set_value
    #   data_template:
    #     entity_id: input_number.window_set_position
    #     value: 74
    # - delay: 00:00:01            
    # - service: input_number.set_value
    #   data_template:
    #     entity_id: input_number.window_set_position
    #     value: 75
    - service: cover.set_cover_position
      target:
        entity_id: cover.shutter_office
      data:
        position: 70
    - delay: 00:00:30
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching Shutter to half open'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_shutter_menu_buttons.btn                 