- alias: 'Shutter LED toggle Office'
  id: tcb_shutter_toggle_led_office
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_shutter_toggle_led_office'
  actions:
    - action: light.toggle
      data:
        entity_id: light.shutter_office_button_led
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'LED Office toggled'
    - delay: 00:00:01
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_shutter_menu_buttons.btn
