##########################################
## INLINE_KEYBOARD - TCB_shutter_close_all
##
- alias: 'TCB_shutter_close_all'
  id: tcb_shutter_close_all
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_shutter_close_all'
  actions:
    - action: cover.close_cover
      target:
        entity_id:
          - cover.shutter_office
          - cover.shutter_dinner
          - cover.shutter_sleep
          - cover.shutter_room
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching shutters to close'
    - delay: 00:00:30
    - action: telegram_bot.delete_message
      data:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'