homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  server_port: 8123
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - yeelight    

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#https://home-assistant.io/components/recorder/
#The recorder component is storing details in a database which then are handled by the history component.
recorder:
  purge_interval: 7
  purge_keep_days: 7

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

###  Sensors  ###
#  Sensors are anything (hardware or software) that has a state.
sensor: !include_dir_merge_list sensors

binary_sensor: !include binary_sensors.yaml
device_tracker: !include device_tracker.yaml

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

#embeded
#mqtt:
#  password: !secret mqttpassword
  
#mosquitto
mqtt:
  broker: 192.168.0.3
  port: 1883
  discovery: False

switch: !include config/switches.yaml
light: !include config/lights.yaml
group: !include_dir_merge_named groups
#panel_iframe: !include panels/panels.yaml
weblink: !include panels/weblinks.yaml
automation: !include_dir_merge_list automations
notify: !include_dir_merge_list notify
script: !include scripts.yaml

#integracio en telegram
telegram_bot:
- platform: polling
  api_key: !secret api_key_telegram
  allowed_chat_ids: 
   - !secret id_group_telegram
   - !secret id_user_telegram
     
### Input Boolean ###
# The input_boolean component allows the user to define boolean values that can be controlled via the frontend and can be used within conditions of automation.
input_boolean: !include input_boolean.yaml

### Input Number ###
input_number: !include input_number.yaml

### Input Select ###
input_select: !include input_select.yaml

media_player:
  - platform: kodi
    host: 192.168.0.106
    tcp_port: !secret kodi_tcp_port
    username: !secret kodi_username
    password: !secret kodi_password

cast:
  media_player:
      - host: 192.168.0.108
      
camera: !include_dir_merge_list cameras

api:

alexa:
  smart_home:

#logger:
#  default: debug