homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


sensor:
# Weather prediction
  #- platform: yr
  #- platform: template
  #  sensors:
  #    yr:
  #      value_template: '{%set list2 = "0","Clear sky","Fair","Partly cloudy","Cloudy","Rain showers","Rain showers and thunder","Sleet showers","Snow showers","Rain","Heavy rain","Heavy rain and thunder","Sleet","Snow","Snow and thunder","Fog","Sleet showers and thunder","Snow showers and thunder","Rain and thunder","Sleet and thunder","Light rain showers and thunder","Heavy rain showers and thunder","Light sleet showers and thunder","Heavy sleet showers and thunder","Light snow showers and thunder","Heavy snow showers and thunder","Light rain and thunder","Light sleet and thunder","Heavy sleet and thunder","Light snow and thunder","Heavy snow and thunder","Light rain showers","Heavy rain showers","Light sleet showers","Heavy sleet showers","Light snow showers","Heavy snow showers","Light rain","Light sleet","Heavy sleet","Light snow","Heavy snow"%}{{list2[states.sensor.yr_symbol.state|int]}}'
  #      entity_picture_template: "{{ state_attr('sensor.yr_symbol','entity_picture') }}"
    #name: Oratge
    #forecast: 24
    #monitored_conditions:
    #  - temperature
    #  - symbol
    #  - precipitation
    #  - windSpeed
    #  - pressure
    #  - windDirection
    #  - humidity
    #  - fog
    #  - cloudiness
    #  - lowClouds
    #  - mediumClouds
    #  - highClouds
    #  - dewpointTemperature
    
    
    #sensor clientraw
    #reads info from clientraw.txt from meteo stations on Internet from URL.
    #needs .homeassistant/custom_components/sensor/clientraw.py
    #from: https://github.com/pilotak/HomeAssistant-MyConfig/tree/master/custom_components/sensor
  - platform: clientraw
    interval: 5
    name: meteocarlet
    url: !secret clientrawURL
    monitored_conditions:
      - temp
      - wind_dir
      - wind_gust_kph
      - wind_kph
      - symbol
      - forecast
      - rain_rate
      - pressure
      - humidity

  - platform: clientraw
    interval: 5
    name: meteoinsti
    url: !secret clientrawURL2
    monitored_conditions:
      - temp
      - wind_dir
      - wind_gust_kph
      - wind_kph
      - symbol
      - forecast
      - rain_rate
      - pressure
      - humidity

  #- platform: template
  #  sensors:
  #    meteocarlet_symbol:
  #      friendly_name: "meteocarlet symbol"
  #      value_template: '{%set list = "sunny", "clearnight", "cloudy", "cloudy2", "night cloudy", "dry", "fog", "haze", "heavyrain", "mainlyfine", "mist", "night fog", "night heavyrain", "night overcast", "night rain", "night showers", "night snow", "night", "thunder", "overcast", "partlycloudy", "rain", "rain2", "showers2", "sleet", "sleetshowers", "snow", "snowmelt", "snowshowers2", "sunny", "thundershowers", "thundershowers2", "thunderstorms", "tornado", "windy", "stopped", "rainning", "wind + rain"%}{{list[states.sensor.meteocarlet_symbol.state-1|int]}}'
      
  # sensor netdata
  - platform: netdata
    resources:
      load:
        data_group: system.load
        element: load15
      cpu:
        data_group: system.cpu
        element: system

# sensor systemmonitor
  - platform: systemmonitor
    #name: MonitorSistema
    #en segons (1 hora)
    #scan_interval: 3600 
    resources:
        - type: disk_use_percent
          arg: /home
        - type: memory_free
        - type: processor_use
        - type: last_boot
        - type: since_last_boot

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
panel_iframe: !include panels/panels.yaml
automation: !include_dir_merge_list automations
notify: !include_dir_merge_list notify
script: !include scripts.yaml

#integracio en telegram
telegram_bot:
- platform: polling
  api_key: !secret api_key_telegram
  allowed_chat_ids: 
   - !secret id_group_telegram
   - !secret id_user_telegram