#requires nmap on debian:
# sudo apt-get install net-tools nmap

#- platform: nmap_tracker
#  hosts: 192.168.0.1/24
#  interval_seconds: 60
#  consider_home: 180
#  scan_options: " –privileged -sP –host-timeout 3s "
#  new_device_defaults:
#      track_new_devices: True
#      hide_if_away: False

#requires installing pybluez:
#   sudo apt-get install bluetooth libbluetooth-dev
#   sudo python3 -m pip install pybluez
#also adding pi to bluetooth group:
#   https://raspberrypi.stackexchange.com/questions/71333/bluetooth-does-not-work-with-raspbian-stretch-and-raspberry-pi-3
#   sudo python3 -m pip install pybluez
#also ensure that known_devices.yaml is property of homeassistant:homeassistant
#   sudo chown homeassistant:homeassistant known_devices.yaml
- platform: bluetooth_tracker
  consider_home: 180
  new_device_defaults:
    track_new_devices: False