##########################################
## INLINE_KEYBOARD - TCB_wcfan_5
##
- alias: 'TCB_wcfan_5'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_wcfan_5'
  action:
    - data:
        duration: 00:05:00
        entity_id: timer.timer_sonoff_basic_2
      service: timer.start
    - service: switch.turn_on
      data:
        entity_id:
          - switch.ventilador_wc    
    - delay: 00:00:01
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'WC Fan on for 5 minutes'       
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_wcfan_menu_buttons.btn