##########################################
## INLINE_KEYBOARD - TCB_wcfan_on
##
- alias: 'TCB_wcfan_on'
  initial_state: 'true'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_wcfan_on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.ventilador_wc
    - delay: 00:00:01
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching WC Fan on'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_wcfan_menu_buttons.btn