##########################################
## INLINE_KEYBOARD - TCB_wcfan_timerstopped
##
- alias: 'TCB_wcfan_timerstopped'
  id: tcb_wcfan_timerstopped
  initial_state: true
  triggers:
  - event_data:
      entity_id: timer.timer_sonoff_basic_2
    event_type: timer.finished
    trigger: event
  conditions: []
  actions:
    - action: switch.turn_off
      data:
        entity_id:
          - switch.ventilador_wc
    - delay: 00:00:01
    - action: telegram_bot.send_message
      data:
        message: 'WC Fan timer ended'
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: !secret id_group_telegram
        inline_keyboard: !include TCB_wcfan_menu_buttons.btn