##########################################
## INLINE_KEYBOARD - TCB_wcfan_off
##
- alias: 'TCB_wcfan_off'
  id: tcb_wcfan_off
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_wcfan_off'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching WC Fan off'
    - action: switch.turn_off
      data:
        entity_id:
          - switch.ventilador_wc
    - delay: 00:00:01
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_wcfan_menu_buttons.btn