##########################################
## INLINE_KEYBOARD - TCB_wcfan_15
##
- alias: 'TCB_wcfan_15'
  id: tcb_wcfan_15
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_wcfan_15'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'WC Fan on for 15 minutes'
    - action: timer.start
      data:
        duration: 00:15:00
        entity_id: timer.timer_sonoff_basic_2
    - action: switch.turn_on
      data:
        entity_id:
          - switch.ventilador_wc
    - delay: 00:00:01
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_wcfan_menu_buttons.btn