##########################################
## INLINE_KEYBOARD - TCB_wcfan_stoptimer
##
- alias: 'TCB_wcfan_stoptimer'
  id: tcb_wcfan_stoptimer
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_wcfan_stoptimer'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'WC Fan timer ended'
    - action: timer.finish
      data:
        entity_id: timer.timer_sonoff_basic_2
    - delay: 00:00:01
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_wcfan_menu_buttons.btn