##########################################
## INLINE_KEYBOARD - TCB_pipedmusic_source_stop
##
- alias: 'TCB_pipedmusic_source_stop'
  id: tcb_pipedmusic_source_stop
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_pipedmusic_source_stop'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching pipedmusic to STOP'
    - action: media_player.media_stop
      data:
        entity_id: media_player.speaker
    - delay: 00:00:03
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_pipedmusic_menu_buttons.btn