##########################################
## INLINE_KEYBOARD - TCB_pipedmusic_menu
##
- alias: 'TCB_pipedmusic_menu'
  id: tcb_pipedmusic_menu
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_pipedmusic_menu'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Piped music menu selected'
    - action: telegram_bot.edit_message
      data:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        message: "\U0001f4e2 ***Piped music*** \U0001f4e2"
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_pipedmusic_menu_buttons.btn

