##########################################
## INLINE_KEYBOARD - TCB_pipedmusic_rockfm_off
##
- alias: 'TCB_pipedmusic_source_stop'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_pipedmusic_source_stop'
  action:
    - service: media_player.media_stop
      data:
        entity_id: media_player.speaker
        source: RockFM      
    - delay: 00:00:03
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching pipedmusic to STOP'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_pipedmusic_menu_buttons.btn