##########################################
## INLINE_KEYBOARD - TCB_pipedmusic_volume_up
##
- alias: 'TCB_pipedmusic_volume_up'
  id: tcb_pipedmusic_volume_up
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_pipedmusic_volume_up'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Volume up'
    - action: media_player.volume_up
      data:
        entity_id: media_player.speaker
    - delay: 00:00:01
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_pipedmusic_menu_buttons.btn