##########################################
## INLINE_KEYBOARD - TCB_pipedmusic_volume_up_up
##
- alias: 'TCB_pipedmusic_volume_up_up'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_pipedmusic_volume_up_up'
  action:
    - service: media_player.volume_up
      data:
        entity_id: media_player.speaker
    - service: media_player.volume_up
      data:
        entity_id: media_player.speaker
    - service: media_player.volume_up
      data:
        entity_id: media_player.speaker
    - delay: 00:00:01
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Volume up up'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_pipedmusic_menu_buttons.btn