##########################################
## INLINE_KEYBOARD - TCB_socket_musiccentral_off
##
- alias: 'TCB_socket_musiccentral_off'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_socket_musiccentral_off'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.sonoffbasic_3
    - delay: 00:00:01
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching music central socket off'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_pipedmusic_menu_buttons.btn