##########################################
## INLINE_KEYBOARD - TCB_pipedmusic_kissfm_on
##
- alias: 'TCB_pipedmusic_kissfm_on'
  id: tcb_pipedmusic_kissfm_on
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_pipedmusic_kissfm_on'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching pipedmusic to KissFM'
    - action: media_player.select_source
      data:
        entity_id: media_player.speaker
        source: KissFM
    - delay: 00:00:07
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_pipedmusic_menu_buttons.btn