##########################################
## Athom
##

homeassistant:
  customize:
    switch.athom_01:
      friendly_name: "Microondas"
    script.athom_01_reset:
      icon: mdi:restore
      friendly_name: "Reset"
    automation.athom_01_switch_left_on:
      icon: mdi:power-plug-off
      friendly_name: "Auto power off"
    sensor.athom_01_power:
      friendly_name: "Power"
      device_class: power
      state_class: measurement
    sensor.athom_01_current:
      friendly_name: "Current"
    sensor.athom_01_voltage:
      friendly_name: "Voltage"
    sensor.athom_01_today:
      friendly_name: "kWh Today"
    sensor.athom_01_total:
      friendly_name: "kWh Total"
    sensor.athom_01_totalstarttime:
      friendly_name: "Last reset"

switch:
  - platform: mqtt
    name: "Athom_01"
    state_topic: "stat/Athom_01/POWER"
    command_topic: "cmnd/Athom_01/POWER"
    availability_topic: "tele/Athom_01/LWT"
    qos: 2
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    icon: mdi:speedometer

sensor:
  - platform: mqtt
    name: athom_01_totalstarttime
    state_topic: "tele/Athom_01/SENSOR"
    value_template: "{{ as_timestamp(strptime(value_json['ENERGY'].TotalStartTime, '%Y-%m-%dT%H:%M:%S%z', now())) | timestamp_custom('%d/%m/%Y %H:%M:%S' ) }}"
    unit_of_measurement: ""
    icon: mdi:update
    
  - platform: mqtt
    name: athom_01_total
    state_topic: "tele/Athom_01/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"
    icon: mdi:elevation-rise
  
  - platform: mqtt
    name: athom_01_today
    state_topic: "tele/Athom_01/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"  
    icon: mdi:elevation-rise
    
  - platform: mqtt
    name: athom_01_power
    state_topic: "tele/Athom_01/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
    icon: mdi:elevation-rise

  - platform: mqtt
    name: athom_01_voltage
    state_topic: "tele/Athom_01/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
    icon: mdi:current-ac

  - platform: mqtt
    name: athom_01_current
    state_topic: "tele/Athom_01/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"
    icon: mdi:transfer

  - platform: template
    sensors:
      athom_01_energy:
        device_class: energy
        friendly_name: "Energy {{state_attr('switch.Athom_01', 'friendly_name')}}"
        attribute_templates:
          state_class: total_increasing
          device_class: energy
        unit_of_measurement: 'kWh'
        value_template: "{{ states('sensor.athom_01_total') }}"
        icon_template: mdi:mdi-current-ac

utility_meter:
  athom_01_hourly_energy:
    source: sensor.athom_01_total
    cycle: hourly
  athom_01_daily_energy:
    source: sensor.athom_01_total
    cycle: daily
  athom_01_monthly_energy:
    source: sensor.athom_01_total
    cycle: monthly
  athom_01_yearly_energy:
    source: sensor.athom_01_total
    cycle: yearly

automation:
  - alias: athom_01_switch_left_on
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: sensor.athom_01_power
        below: 30
        above: 1
        for:
          minutes: 1
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.athom_01
      - delay: 0:00:02
      - service: notify.homeassistant
        data:
          message: 
            "{{state_attr('switch.athom_01', 'friendly_name')}} switch is now **{% if is_state('switch.athom_01', 'on') %}ON{% else %}OFF{% endif %}** because it was consuming less than 30W for 1 minutes"          
      - delay: 0:00:02
      - service: persistent_notification.create
        data:
          message: "Is now **{% if is_state('switch.athom_01', 'on') %}ON{% else %}OFF{% endif %}** because it was left on for 1 minutes"
          title: "{{state_attr('switch.athom_01', 'friendly_name')}}"

script:
  athom_01_reset:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "cmnd/Athom_01/energyreset1"
          payload: "0"
      - service: mqtt.publish
        data_template:
          topic: "cmnd/Athom_01/energyreset2"
          payload: "0"
      - service: mqtt.publish
        data_template:
          topic: "cmnd/Athom_01/energyreset3"
          payload: "0"

#########################
#Lovelace entities Card:#
#########################
# entities:
#   - entity: switch.athom_01
#   - entity: sensor.athom_01_power
#   - entity: sensor.athom_01_current
#   - entity: sensor.athom_01_voltage
#   - entity: sensor.athom_01_totalstarttime
#   - entity: sensor.athom_01_today
#   - entity: sensor.athom_01_total
#   - entity: script.athom_01_reset
#   - entity: automation.athom_01_switch_left_on
# show_header_toggle: false
# type: entities