##########################################
## BlitzWolf SHP2 http://192.168.3.89
## medidorconsumo2
##
homeassistant:
  customize:
    switch.blitzw0lf_6:
      friendly_name: "Tele"
    script.bw6_report:
      icon: mdi:message-reply-text  
      friendly_name: "Report"
    script.bw6_reset:
      icon: mdi:restore
      friendly_name: "Reset"
    sensor.bw6_power:
      friendly_name: "Power"
    sensor.bw6_current:
      friendly_name: "Current"
    sensor.bw6_voltage:
      friendly_name: "Voltage"
    sensor.bw6_today:
      friendly_name: "KW Today"
    sensor.bw6_total:
      friendly_name: "KW Total"
    sensor.bw6_totalstarttime:
      friendly_name: "Last reset"

input_number:
  bw6_kw_pico:
    name: 'KW pico'
    icon: mdi:trending-up
    unit_of_measurement: "KW"
    min: 0
    max: 1000
    mode: box
    step: 0.001 
  bw6_kw_valle:
    name: 'KW valle'
    icon: mdi:trending-down
    unit_of_measurement: "KW"
    min: 0
    max: 1000
    mode: box
    step: 0.001 
  bw6_partial:
    name: partial data
    icon: mdi:calculator-variant
    unit_of_measurement: "KW"
    min: 0
    max: 1000
    mode: box
    step: 0.001  

switch:
  - platform: mqtt
    name: "BliTZW0lF_6"
    state_topic: "stat/BliTZW0lF_6/POWER"
    command_topic: "cmnd/BliTZW0lF_6/POWER"
    availability_topic: "tele/BliTZW0lF_6/LWT"
    qos: 2
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    icon: mdi:speedometer

sensor:
  - platform: mqtt
    name: bw6_totalstarttime
    state_topic: "tele/BliTZW0lF_6/SENSOR"
    value_template: "{{ as_timestamp(strptime(value_json['ENERGY'].TotalStartTime, '%Y-%m-%dT%H:%M:%S%z')) | timestamp_custom('%d/%m/%Y %H:%M:%S' ) }}"
    unit_of_measurement: ""
    icon: mdi:update
    
  - platform: mqtt
    name: bw6_total
    state_topic: "tele/BliTZW0lF_6/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "KW"
    icon: mdi:elevation-rise
  
  - platform: mqtt
    name: bw6_today
    state_topic: "tele/BliTZW0lF_6/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "KW"  
    icon: mdi:elevation-rise
    
  - platform: mqtt
    name: bw6_power
    state_topic: "tele/BliTZW0lF_6/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
    icon: mdi:elevation-rise

  - platform: mqtt
    name: bw6_voltage
    state_topic: "tele/BliTZW0lF_6/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
    icon: mdi:current-ac

  - platform: mqtt
    name: bw6_current
    state_topic: "tele/BliTZW0lF_6/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"
    icon: mdi:transfer

  - platform: template
    sensors:
      bw6_kw_valle:
        friendly_name: 'KW valle'
        value_template: '{{ (states("input_number.bw6_kw_valle") | float| round(6)) }}'
        icon_template: mdi:trending-down
        unit_of_measurement: "KW"
      bw6_kw_pico:
        friendly_name: 'KW pico'
        value_template: '{{ (states("input_number.bw6_kw_pico") | float | round(6)) }}'
        icon_template: mdi:trending-up
        unit_of_measurement: "KW"
      bw6_eur_valle:
        friendly_name: '€ valle'
        value_template: '{{ (states("input_number.bw6_kw_valle") | multiply(0.086565 ) | float | round(2)) }}'
        unit_of_measurement: "€"
        icon_template: mdi:progress-download
      bw6_eur_pico:
        friendly_name: '€ pico'
        value_template: '{{ (states("input_number.bw6_kw_pico") | multiply(0.165323) | float | round(2)) }}'
        icon_template: mdi:progress-upload
        unit_of_measurement: "€"
      bw6_total_euro:
        friendly_name: '€ Total'
        value_template: '{{(((states.sensor.bw6_eur_valle.state | float) + (states.sensor.bw6_eur_pico.state  | float)) | round(2)) }}'
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur   

automation:
  - alias: 'bw6 reset'
    initial_state: 'true'
    trigger:
      - platform: template
        value_template: '{{ now().strftime("%d") == "01" }}'
    action:
      - service: script.bw6_report
      - service: script.bw7_reset
        
  - alias: 'bw6 Valle'
    initial_state: on
    trigger:
      - platform: template
        value_template: '{{ now().strftime("%M") == "00" }}'
    condition:
      - condition: template
        value_template: '{{ now().strftime("%H") == "13" }}'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bw6_kw_valle
          value: "{{ ((states.input_number.bw6_kw_valle.state|float) + ((states.sensor.bw6_total.state|float) - (states.input_number.bw6_partial.state|float))|float) }}"
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bw6_partial
          value: "{{ states.sensor.bw6_total.state }}"          

  - alias: 'bw6 Pico'
    initial_state: on
    trigger:
      - platform: template
        value_template: '{{ now().strftime("%M") == "00" }}'
    condition:
      - condition: template
        value_template: '{{ now().strftime("%H") == "23" }}'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bw6_kw_pico
          value: "{{ ((states.input_number.bw6_kw_pico.state|float) + ((states.sensor.bw6_total.state|float) - (states.input_number.bw6_partial.state|float))|float) }}"
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bw6_partial
          value: "{{ states.sensor.bw6_total.state }}"      

script:
  bw6_report:
    sequence:
      - service: persistent_notification.create
        data_template:
          title: "{{state_attr('switch.blitzw0lf_6', 'friendly_name')}} Report"
          message: "From {{ (states.sensor.bw6_totalstarttime.state) | timestamp_custom('%d/%m/%Y %H:%M:%S' )}}\n
            to {{ as_timestamp(now()) | timestamp_custom('%d/%m/%Y %H:%M:%S' )}}\n\n
            KW Pico: {{ states.sensor.bw6_kw_pico.state_with_unit }} \n
            KW Vall: {{ states.sensor.bw6_kw_valle.state_with_unit }} \n
            Total KW: {{ states.sensor.bw6_total.state_with_unit }}\n\n
            € Pico: {{ states.sensor.bw6_eur_pico.state_with_unit }} \n
            € Vall: {{ states.sensor.bw6_eur_valle.state_with_unit }} \n
            Total €: {{ states.sensor.bw6_total_euro.state_with_unit }}\n"
  bw6_reset:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "cmnd/BliTZW0lF_6/energyreset1"
          payload: "0"
      - service: mqtt.publish
        data_template:
          topic: "cmnd/BliTZW0lF_6/energyreset2"
          payload: "0"
      - service: mqtt.publish
        data_template:
          topic: "cmnd/BliTZW0lF_6/energyreset3"
          payload: "0"
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bw6_Kw_pico
          value: "0"
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bw6_Kw_valle
          value: "0"
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bw6_partial
          value: "0"

# group:
#   BliTZW0lF_6:
#     name: blitz6
#     icon: mdi:fish
#     entities:
#       - switch.BliTZW0lF_6
#       - sensor.bw6_power
#       - sensor.bw6_current
#       - sensor.bw6_voltage
#       - sensor.bw6_today
#       - sensor.bw6_totalstarttime
#       - sensor.bw6_kw_pico
#       - sensor.bw6_kw_valle
#       - sensor.bw6_total   
#       - sensor.bw6_eur_pico
#       - sensor.bw6_eur_valle
#       - sensor.bw6_total_euro
#       - automation.bw6_reset
#       - script.bw6_report
#       - input_number.bw6_partial
#       - automation.bw6_valle
#       - automation.bw6_pico 

# smart_home:
#   entity_config:
#     switch.BliTZW0lF_6:
#       name: "Lámpara comedor"
#       description: "Lámpara comedor"
#       display_categories: SMARTPLUG