##########################################
## BlitzWolf SHP2
##

homeassistant:
  customize:
    switch.BliTZW0lF_2:
      friendly_name: "Impresora 3d"
    automation.bw2_switch_left_on:
      icon: mdi:power-plug-off
      friendly_name: "Auto power off"
    script.bw2_reset:
      icon: mdi:restore
      friendly_name: "Reset"
    sensor.bw2_power:
      friendly_name: "Power"
      device_class: power
      state_class: measurement      
    sensor.bw2_current:
      friendly_name: "Current"
    sensor.bw2_voltage:
      friendly_name: "Voltage"
    sensor.bw2_today:
      friendly_name: "kWh Today"
    sensor.bw2_total:
      friendly_name: "kWh Total"
    sensor.bw2_totalstarttime:
      friendly_name: "Last reset"

mqtt:
  switch:
  - name: "BliTZW0lF_2"
    state_topic: "stat/BliTZW0lF_2/POWER"
    command_topic: "cmnd/BliTZW0lF_2/POWER"
    availability_topic: "tele/BliTZW0lF_2/LWT"
    qos: 2
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    icon: mdi:speedometer

  sensor:
  - name: bw2_totalstarttime
    state_topic: "tele/BliTZW0lF_2/SENSOR"
    value_template: "{{ as_timestamp(strptime(value_json['ENERGY'].TotalStartTime, '%Y-%m-%dT%H:%M:%S%z', now())) | timestamp_custom('%d/%m/%Y %H:%M:%S' ) }}"
    unit_of_measurement: ""
    icon: mdi:update
    
  - name: bw2_total
    state_topic: "tele/BliTZW0lF_2/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"
    icon: mdi:elevation-rise
  
  - name: bw2_today
    state_topic: "tele/BliTZW0lF_2/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"  
    icon: mdi:elevation-rise
    
  - name: bw2_power
    state_topic: "tele/BliTZW0lF_2/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
    icon: mdi:elevation-rise

  - name: bw2_voltage
    state_topic: "tele/BliTZW0lF_2/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
    icon: mdi:current-ac

  - name: bw2_current
    state_topic: "tele/BliTZW0lF_2/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"
    icon: mdi:transfer

# sensor:
#   - platform: template
#     sensors:
#       bw2_energy:
#         device_class: energy
#         friendly_name: "Energy {{state_attr('switch.BliTZW0lF_2', 'friendly_name')}}"
#         attribute_templates:
#           state_class: total_increasing
#           device_class: energy
#         unit_of_measurement: 'kWh'
#         value_template: "{{ states('sensor.bw2_total') }}"
#         icon_template: mdi:mdi-current-ac

utility_meter:
  bw2_hourly_energy:
    source: sensor.bw2_total
    cycle: hourly
  bw2_daily_energy:
    source: sensor.bw2_total
    cycle: daily
  bw2_monthly_energy:
    source: sensor.bw2_total
    cycle: monthly
  bw2_yearly_energy:
    source: sensor.bw2_total
    cycle: yearly

  # bw2_monthly_energy_cost:
  #   source: sensor.bw2_energy_cost_hour
  #   cycle: monthly

automation:
  # - alias: 'bw2 reset'
  #   initial_state: true
  #   trigger:
  #     - platform: template
  #       value_template: '{{ now().strftime("%d") == "01" }}'
  #   action:
  #     - service: script.bw2_report
  #     - service: script.bw2_reset
  # - alias: 'bw2 Valle'
  #   initial_state: on
  #   trigger:
  #     - platform: template
  #       value_template: '{{ now().strftime("%M") == "00" }}'
  #   condition:
  #     - condition: template
  #       value_template: '{{ now().strftime("%H") == "13" }}'
  #   action:
  #     - service: input_number.set_value
  #       data_template:
  #         entity_id: input_number.bw2_kw_valle
  #         value: "{{ ((states.input_number.bw2_kw_valle.state|float) + ((states.sensor.bw2_total.state|float) - (states.input_number.bw2_partial.state|float))|float) }}"
  #     - service: input_number.set_value
  #       data_template:
  #         entity_id: input_number.bw2_partial
  #         value: "{{ states.sensor.bw2_total.state }}"          

  # - alias: 'bw2 Pico'
  #   initial_state: on
  #   trigger:
  #     - platform: template
  #       value_template: '{{ now().strftime("%M") == "00" }}'
  #   condition:
  #     - condition: template
  #       value_template: '{{ now().strftime("%H") == "23" }}'
  #   action:
  #     - service: input_number.set_value
  #       data_template:
  #         entity_id: input_number.bw2_kw_pico
  #         value: "{{ ((states.input_number.bw2_kw_pico.state|float) + ((states.sensor.bw2_total.state|float) - (states.input_number.bw2_partial.state|float))|float) }}"
  #     - service: input_number.set_value
  #       data_template:
  #         entity_id: input_number.bw2_partial
  #         value: "{{ states.sensor.bw2_total.state }}"

  - alias: bw2_switch_left_on
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: sensor.bw2_power
        below: 30
        above: 1
        for:
          minutes: 5
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.BliTZW0lF_2
      - delay: 0:00:02
      - service: notify.send_message
        data:
          entity_id: notify.telegram_bot_701350878_327910374
          message: 
            "{{state_attr('switch.BliTZW0lF_2', 'friendly_name')}} switch is now **{% if is_state('switch.BliTZW0lF_2', 'on') %}ON{% else %}OFF{% endif %}** because it was consuming less than 30W for 5 minutes"          
      - delay: 0:00:02
      - service: persistent_notification.create
        data:
          message: "Is now **{% if is_state('switch.BliTZW0lF_2', 'on') %}ON{% else %}OFF{% endif %}** because it was left on for 5 minutes"
          title: "{{state_attr('switch.BliTZW0lF_2', 'friendly_name')}}"

script:
  # bw2_report:
  #   sequence:
  #     - service: persistent_notification.create
  #       data_template:
  #         title: "{{state_attr('switch.BliTZW0lF_2', 'friendly_name')}} Report"
  #         message: "From {{ (states.sensor.bw2_totalstarttime.state) | timestamp_custom('%d/%m/%Y %H:%M:%S' )}}\n
  #           to {{ as_timestamp(now()) | timestamp_custom('%d/%m/%Y %H:%M:%S' )}}\n\n
  #           KW Pico: {{ states.sensor.bw2_kw_pico.state_with_unit }} \n
  #           KW Vall: {{ states.sensor.bw2_kw_valle.state_with_unit }} \n
  #           Total KW: {{ states.sensor.bw2_total.state_with_unit }}\n\n
  #           € Pico: {{ states.sensor.bw2_eur_pico.state_with_unit }} \n
  #           € Vall: {{ states.sensor.bw2_eur_valle.state_with_unit }} \n
  #           Total €: {{ states.sensor.bw2_total_euro.state_with_unit }}\n"
  bw2_reset:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "cmnd/BliTZW0lF_2/energyreset1"
          payload: "0"
      - service: mqtt.publish
        data_template:
          topic: "cmnd/BliTZW0lF_2/energyreset2"
          payload: "0"
      - service: mqtt.publish
        data_template:
          topic: "cmnd/BliTZW0lF_2/energyreset3"
          payload: "0"

#########################
#Lovelace entities Card:#
#########################
# entities:
#   - entity: switch.BliTZW0lF_2
#   - entity: sensor.bw2_power
#   - entity: sensor.bw2_current
#   - entity: sensor.bw2_voltage
#   - entity: sensor.bw2_totalstarttime
#   - entity: sensor.bw2_today
#   - entity: sensor.bw2_total
#   - entity: script.bw2_reset
#   - entity: automation.bw2_switch_left_on
# show_header_toggle: false
# type: entities