##########################################
## BlitzWolf SHP2
##

homeassistant:
  customize:
    switch.BliTZW0lF_1:
      friendly_name: "Calentador"
    automation.bw1_switch_left_on:
      icon: mdi:power-plug-off
      friendly_name: "Auto power off"
    script.bw1_reset:
      icon: mdi:restore
      friendly_name: "Reset"
    sensor.bw1_power:
      friendly_name: "Power"
      device_class: power
      state_class: measurement
    sensor.bw1_current:
      friendly_name: "Current"
    sensor.bw1_voltage:
      friendly_name: "Voltage"
    sensor.bw1_today:
      friendly_name: "kWh Today"
    sensor.bw1_total:
      friendly_name: "kWh Total"
    sensor.bw1_totalstarttime:
      friendly_name: "Last reset"

mqtt:
  switch:
  - name: "BliTZW0lF_1"
    state_topic: "stat/BliTZW0lF_1/POWER"
    command_topic: "cmnd/BliTZW0lF_1/POWER"
    availability_topic: "tele/BliTZW0lF_1/LWT"
    qos: 2
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    icon: mdi:speedometer

  sensor:
  - name: bw1_totalstarttime
    state_topic: "tele/BliTZW0lF_1/SENSOR"
    value_template: "{{ as_timestamp(strptime(value_json['ENERGY'].TotalStartTime, '%Y-%m-%dT%H:%M:%S%z', now())) | timestamp_custom('%d/%m/%Y %H:%M:%S' ) }}"
    unit_of_measurement: ""
    icon: mdi:update
    
  - name: bw1_total
    state_topic: "tele/BliTZW0lF_1/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"
    icon: mdi:elevation-rise
  
  - name: bw1_today
    state_topic: "tele/BliTZW0lF_1/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"  
    icon: mdi:elevation-rise
    
  - name: bw1_power
    state_topic: "tele/BliTZW0lF_1/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
    icon: mdi:elevation-rise

  - name: bw1_voltage
    state_topic: "tele/BliTZW0lF_1/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
    icon: mdi:current-ac

  - name: bw1_current
    state_topic: "tele/BliTZW0lF_1/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"
    icon: mdi:transfer

# sensor:
#   - platform: template
#     sensors:
#       bw1_energy:
#         device_class: energy
#         friendly_name: "Energy {{state_attr('switch.BliTZW0lF_1', 'friendly_name')}}"
#         attribute_templates:
#           state_class: total_increasing
#           device_class: energy
#         unit_of_measurement: 'kWh'
#         value_template: "{{ states('sensor.bw1_total') }}"
#         icon_template: mdi:mdi-current-ac

utility_meter:
  bw1_hourly_energy:
    source: sensor.bw1_total
    cycle: hourly
  bw1_daily_energy:
    source: sensor.bw1_total
    cycle: daily
  bw1_monthly_energy:
    source: sensor.bw1_total
    cycle: monthly
  bw1_yearly_energy:
    source: sensor.bw1_total
    cycle: yearly

automation:
  - alias: bw1_switch_left_on
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: sensor.bw1_power
        below: 30
        above: 1
        for:
          minutes: 5
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.BliTZW0lF_1
      - delay: 0:00:02
      - service: notify.send_message
        data:
          entity_id: notify.telegram_bot_701350878_327910374
          message: 
            "{{state_attr('switch.BliTZW0lF_1', 'friendly_name')}} switch is now **{% if is_state('switch.BliTZW0lF_1', 'on') %}ON{% else %}OFF{% endif %}** because it was consuming less than 30W for 5 minutes"          
      - delay: 0:00:02
      - service: persistent_notification.create
        data:
          message: "Is now **{% if is_state('switch.BliTZW0lF_1', 'on') %}ON{% else %}OFF{% endif %}** because it was left on for 5 minutes"
          title: "{{state_attr('switch.BliTZW0lF_1', 'friendly_name')}}"

script:
  bw1_reset:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "cmnd/BliTZW0lF_1/energyreset1"
          payload: "0"
      - service: mqtt.publish
        data_template:
          topic: "cmnd/BliTZW0lF_1/energyreset2"
          payload: "0"
      - service: mqtt.publish
        data_template:
          topic: "cmnd/BliTZW0lF_1/energyreset3"
          payload: "0"

#########################
#Lovelace entities Card:#
#########################
# entities:
#   - entity: switch.BliTZW0lF_1
#   - entity: sensor.bw1_power
#   - entity: sensor.bw1_current
#   - entity: sensor.bw1_voltage
#   - entity: sensor.bw1_totalstarttime
#   - entity: sensor.bw1_today
#   - entity: sensor.bw1_total
#   - entity: script.bw1_reset
#   - entity: automation.bw1_switch_left_on
# show_header_toggle: false
# type: entities


##REVISAR!!!
# blitzwolf1_report:
#   sequence:
#     - service: persistent_notification.create
#       data_template:
#         title: "Blitwolf1 Report"
#         message: "From {{ (states.sensor.bw1_totalstarttime.state) | timestamp_custom('%d/%m/%Y %H:%M:%S' )}}\n
#                   to {{ as_timestamp(now()) | timestamp_custom('%d/%m/%Y %H:%M:%S' )}}\n\n
#                   KW Pico: {{ states.sensor.sensor_bw1_kw_pico.state_with_unit }} \n
#                   KW Vall: {{ states.sensor.sensor_bw1_kw_valle.state_with_unit }} \n
#                   Total KW: {{ states.sensor.bw1_total.state_with_unit }}\n\n
#                   € Pico: {{ states.sensor.sensor_bw1_eur_pico.state_with_unit }} \n
#                   € Vall: {{ states.sensor.sensor_bw1_eur_valle.state_with_unit }} \n
#                   Total €: {{ states.sensor.sensor_bw1_total_euro.state_with_unit }}\n"

# - alias: 'Blitzwolf1 reset'
#   initial_state: true
#   trigger:
#     - platform: template
#       value_template: '{{ now().strftime("%d") == "01" }}'
#   action:
#     - service: script.blitzwolf1_report
#     - service: mqtt.publish
#       data_template:
#         topic: "cmnd/BliTZW0lF_1/energyreset1"
#         payload: "0"
#     - service: mqtt.publish
#       data_template:
#         topic: "cmnd/BliTZW0lF_1/energyreset2"
#         payload: "0"
#     - service: mqtt.publish
#       data_template:
#         topic: "cmnd/BliTZW0lF_1/energyreset3"
#         payload: "0"
#     - service: input_number.set_value
#       data_template:
#         entity_id: input_number.bw1_Kw_pico
#         value: "0"
#     - service: input_number.set_value
#       data_template:
#         entity_id: input_number.bw1_Kw_valle
#         value: "0"
#     - service: input_number.set_value
#       data_template:
#         entity_id: input_number.bw1_partial
#         value: "0"    