##########################################
## INLINE_KEYBOARD - TCB_start_menu
##
- alias: 'TCB_start_menu'
  initial_state: 'true'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_start_menu'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Main Menu selected'
    - service: telegram_bot.edit_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        message: "\uD83C\uDFE0 ***HA Bot - Main Menu*** \uD83C\uDFE0"
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_start_menu_buttons.btn

