##########################################
## BlitzWolf SHP2 (2.3 http://192.168.0.161
## BliTZW0lF_2 
##

- platform: mqtt
  name: bw2_totalstarttime
  state_topic: "tele/BliTZW0lF_2/SENSOR"
  value_template: "{{ as_timestamp(strptime(value_json['ENERGY'].TotalStartTime, '%Y-%m-%dT%H:%M:%S%z')) | timestamp_custom('%d/%m/%Y %H:%M:%S' ) }}"
  unit_of_measurement: ""
  
- platform: mqtt
  name: bw2_total
  state_topic: "tele/BliTZW0lF_2/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total }}"
  unit_of_measurement: "kW/h"

- platform: mqtt
  name: bw2_total_euro
  state_topic: "tele/BliTZW0lF_2/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total | multiply(0.145) | round(2) }}"
  unit_of_measurement: "€"
    
- platform: mqtt
  name: bw2_yesterday
  state_topic: "tele/BliTZW0lF_2/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday }}"
  unit_of_measurement: "kW/h"  
  
- platform: mqtt
  name: bw2_yesterday_euro
  state_topic: "tele/BliTZW0lF_2/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday | multiply(0.145) | round(2) }}"
  unit_of_measurement: "€"  
  
- platform: mqtt
  name: bw2_today
  state_topic: "tele/BliTZW0lF_2/SENSOR"
  value_template: "{{ value_json['ENERGY'].Today }}"
  unit_of_measurement: "kW/h"  
  
- platform: mqtt
  name: bw2_power
  state_topic: "tele/BliTZW0lF_2/SENSOR"
  value_template: "{{ value_json['ENERGY'].Power }}"
  unit_of_measurement: "W"

- platform: mqtt
  name: bw2_factor
  state_topic: "tele/BliTZW0lF_2/SENSOR"
  value_template: "{{ value_json['ENERGY'].Factor }}"

- platform: mqtt
  name: bw2_voltage
  state_topic: "tele/BliTZW0lF_2/SENSOR"
  value_template: "{{ value_json['ENERGY'].Voltage }}"
  unit_of_measurement: "V"

- platform: mqtt
  name: bw2_current
  state_topic: "tele/BliTZW0lF_2/SENSOR"
  value_template: "{{ value_json['ENERGY'].Current }}"
  unit_of_measurement: "A"