##########################################
## BlitzWolf SHP2 (normal) http://192.168.0.163
## BliTZW0lF_4 
##

- platform: mqtt
  name: bw4_totalstarttime
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ as_timestamp(strptime(value_json['ENERGY'].TotalStartTime, '%Y-%m-%dT%H:%M:%S%z')) | timestamp_custom('%d/%m/%Y %H:%M:%S' ) }}"
  unit_of_measurement: ""
  
- platform: mqtt
  name: bw4_total
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total }}"
  unit_of_measurement: "kW/h"

- platform: mqtt
  name: bw4_total_euro
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total | multiply(0.145) | round(2) }}"
  unit_of_measurement: "€"
    
- platform: mqtt
  name: bw4_yesterday
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday }}"
  unit_of_measurement: "kW/h"  
  
- platform: mqtt
  name: bw4_yesterday_euro
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday | multiply(0.145) | round(2) }}"
  unit_of_measurement: "€"  
  
- platform: mqtt
  name: bw4_today
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Today }}"
  unit_of_measurement: "kW/h"  
  
- platform: mqtt
  name: bw4_power
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Power }}"
  unit_of_measurement: "W"

- platform: mqtt
  name: bw4_factor
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Factor }}"

- platform: mqtt
  name: bw4_voltage
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Voltage }}"
  unit_of_measurement: "V"

- platform: mqtt
  name: bw4_current
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Current }}"
  unit_of_measurement: "A"

###########################################
### BlitzWolf SHP2 (normal) http://192.168.0.163
### BliTZW0lF_4 (espurna)
###
#- name: BliTzW0lf4_current
#  platform: mqtt
#  state_topic: BliTzW0lf4/current
#  unit_of_measurement: A
#
#- name: BliTzW0lf4_voltage
#  platform: mqtt
#  state_topic: BliTzW0lf4/voltage
#  unit_of_measurement: V
#
#- name: BliTzW0lf4_power
#  platform: mqtt
#  state_topic: BliTzW0lf4/power
#  unit_of_measurement: W
#
#- name: BliTzW0lf4_reactive
#  platform: mqtt
#  state_topic: BliTzW0lf4/reactive
#  unit_of_measurement: W
#
#- name: BliTzW0lf4_apparent
#  platform: mqtt
#  state_topic: BliTzW0lf4/apparent
#  unit_of_measurement: W
#
#- name: BliTzW0lf4_factor
#  platform: mqtt
#  state_topic: BliTzW0lf4/factor
#  unit_of_measurement: '%'
#
#- name: BliTzW0lf4_energy
#  platform: mqtt
#  state_topic: BliTzW0lf4/energy
#  unit_of_measurement: J