##########################################
## BlitzWolf SHP2 (normal) http://192.168.0.163
## BliTZW0lF_4 
##

- platform: mqtt
  name: bw4_totalstarttime
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ as_timestamp(strptime(value_json['ENERGY'].TotalStartTime, '%Y-%m-%dT%H:%M:%S%z')) | timestamp_custom('%d/%m/%Y %H:%M:%S' ) }}"
  unit_of_measurement: ""
  icon: mdi:update
  
- platform: mqtt
  name: bw4_total
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total }}"
  unit_of_measurement: "KW"
  icon: mdi:elevation-rise
 
- platform: mqtt
  name: bw4_today
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Today }}"
  unit_of_measurement: "KW"  
  icon: mdi:elevation-rise
  
- platform: mqtt
  name: bw4_power
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Power }}"
  unit_of_measurement: "W"
  icon: mdi:elevation-rise

- platform: mqtt
  name: bw4_voltage
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Voltage }}"
  unit_of_measurement: "V"
  icon: mdi:current-ac

- platform: mqtt
  name: bw4_current
  state_topic: "tele/BliTZW0lF_4/SENSOR"
  value_template: "{{ value_json['ENERGY'].Current }}"
  unit_of_measurement: "A"
  icon: mdi:transfer