- platform: jsonrest
  resource: !secret clientgasolina
  name: gasolinera
  scan_interval: 3600
    
- platform: template
  sensors:      
    gasolinera3:
      friendly_name: CAMPSA EXPRESS
      value_template: >-
              {%- for petrol in states.sensor.gasolinera.attributes.ListaEESSPrecio -%}
                {%- if petrol["IDEESS"] | int  == 12925 -%}  
                  {{ petrol["Precio Gasolina 95 Protección"] | capitalize | replace(",",".") }} 
                {%- endif -%}
              {%- endfor -%}
      unit_of_measurement: '€/L'
    gasolinera5:
      friendly_name: E.S. LA PONDEROSA
      value_template: >-
              {%- for petrol in states.sensor.gasolinera.attributes.ListaEESSPrecio -%}
                {%- if petrol["IDEESS"] | int  == 4113 -%}  
                  {{ petrol["Precio Gasolina 95 Protección"] | capitalize | replace(",",".") }} 
                {%- endif -%}
              {%- endfor -%}
      unit_of_measurement: '€/L'
    gasolinera1:
      friendly_name: E.S. LA REINA
      value_template: >-
              {%- for petrol in states.sensor.gasolinera.attributes.ListaEESSPrecio -%}
                {%- if petrol["IDEESS"] | int  == 4117 -%}  
                  {{ petrol["Precio Gasolina 95 Protección"] | capitalize | replace(",",".") }} 
                {%- endif -%}
              {%- endfor -%}
      unit_of_measurement: '€/L' 
    gasolinera7:
      friendly_name: COOPCARLET
      value_template: >-
              {%- for petrol in states.sensor.gasolinera.attributes.ListaEESSPrecio -%}
                {%- if petrol["IDEESS"] | int  == 11656 -%}  
                  {{ petrol["Precio Gasolina 95 Protección"] | capitalize | replace(",",".") }} 
                {%- endif -%}
              {%- endfor -%}
      unit_of_measurement: '€/L'        
    gasolinera6:
      friendly_name: E.S. EL CORTIJO
      value_template: >-
              {%- for petrol in states.sensor.gasolinera.attributes.ListaEESSPrecio -%}
                {%- if petrol["IDEESS"] | int  == 4114 -%}  
                  {{ petrol["Precio Gasolina 95 Protección"] | capitalize | replace(",",".") }} 
                {%- endif -%}
              {%- endfor -%}
      unit_of_measurement: '€/L'          
    gasolinera2:
      friendly_name: VALCARCE (POLIGONO)
      value_template: >-
              {%- for petrol in states.sensor.gasolinera.attributes.ListaEESSPrecio -%}
                {%- if petrol["IDEESS"] | int  == 10530 -%}  
                  {{ petrol["Precio Gasolina 95 Protección"] | capitalize | replace(",",".") }} 
                {%- endif -%}
              {%- endfor -%}
      unit_of_measurement: '€/L'       
    gasolinera4:
      friendly_name: GASEXPRESS
      value_template: >-
              {%- for petrol in states.sensor.gasolinera.attributes.ListaEESSPrecio -%}
                {%- if petrol["IDEESS"] | int  == 12771 -%}  
                  {{ petrol["Precio Gasolina 95 Protección"] | capitalize | replace(",",".") }} 
                {%- endif -%}
              {%- endfor -%}
      unit_of_measurement: '€/L'

