#sensor clientraw
#reads info from clientraw.txt from meteo stations on Internet from URL.
#needs .homeassistant/custom_components/sensor/clientraw.py
#from: https://github.com/pilotak/HomeAssistant-MyConfig/tree/master/custom_components/sensor
- platform: clientraw
  name: meteoinsti
  url: !secret clientrawURL2
  interval: 5
  monitored_conditions:
    - temp
    - wind_dir
    - wind_gust_kph
    - wind_kph
    - symbol
    - forecast
    - rain_rate
    - pressure
    - humidity