- platform: mqtt  
  state_topic: "dmp/lolin3"
  name: "Lolin3 Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
  
- platform: mqtt  
  state_topic: "dmp/lolin3"
  name: "Lolin3 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  
  
- platform: mqtt  
  state_topic: "dmp/lolin3"
  name: "Lolin3 PIR"
  value_template: '{{ value_json.motion }}'  
  
- platform: mqtt  
  state_topic: "dmp/lolin3"
  name: "Lolin3 Temperature"  
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "dmp/lolin3"
  name: "Lolin3 Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'
