# Octprint Enclosure Plugin
- platform: rest
  name: printer_enclosure_temp
  device_class: temperature
  unit_of_measurement: "°C"
  resource: !secret octopienclosure
  value_template: '{{ value_json.temp_sensor_temp }}'
- platform: rest
  name: printer_enclosure_hum
  device_class: humidity
  unit_of_measurement: "%"
  resource: !secret octopienclosure
  value_template: '{{ value_json.temp_sensor_humidity }}'