# sensor systemmonitor
- platform: systemmonitor
  #name: MonitorSistema
  #en segons (1 hora)
  #scan_interval: 3600 
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: last_boot
#    - type: since_last_boot