- platform: template
  sensors:
    timer1_time:
      friendly_name: 'start time'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.timer1_hour") | int, states("input_number.timer1_minutes") | int) }}'
    timer1_duration:
      friendly_name: 'duration'  
      value_template: '{{ "%0.02d:%0.02d" | format(0 | int, states("input_number.timer1_duration") | int) }}'  
    timer2_time:
      friendly_name: 'start time'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.timer2_hour") | int, states("input_number.timer2_minutes") | int) }}'
    timer2_duration:
      friendly_name: 'duration'  
      value_template: '{{ "%0.02d:%0.02d" | format(0 | int, states("input_number.timer2_duration") | int) }}'