##########################################
## INLINE_KEYBOARD - TCB_socket_roomba_on
##
- alias: 'TCB_socket_roomba_on'
  id: tcb_socket_roomba_on
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_socket_roomba_on'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching Roomba socket on'
    - action: switch.turn_on
      data:
        entity_id:
          - switch.blitzw0lf_5
    - delay: 00:00:01
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_sockets_menu_buttons.btn