- alias: AirFresheners on when home
  trigger:
    - platform: state
      entity_id: device_tracker.oneplus
      from: 'not_home'
      to: 'home'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.sonoffAmbiCorredor
    - service: switch.turn_on
      data:
        entity_id: switch.sonoffAmbiBany
        
- alias: AirFresheners Off when not home
  trigger:
    - platform: state
      entity_id: device_tracker.oneplus
      from: 'home'
      to: 'not_home'
      for:
        minutes: 5
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.sonoffAmbiCorredor
    - service: switch.turn_off
      data:
        entity_id: switch.sonoffAmbiBany
