- alias: 'Front door open Christmas Tree'
  id: christmas_lights_open_door
  initial_state: true
  triggers:
    - trigger: state
      entity_id: 'binary_sensor.front_door'
      to: 'on'
  actions:
    - action: script.christmas_tree