- alias: computer_switch_left_on
  trigger:
    - platform: numeric_state
      entity_id: sensor.bw3_power
      #value_template: {{state.sensor.bw5_power.state}}
      below: 30
      above: 1
      for:
        minutes: 5
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.BliTZW0lF_3
    - delay: 0:00:05
    - service: notify.homeassistant
      data:
        message: 
          "Computer switch is now **{% if is_state('switch.BliTZW0lF_3', 'on') %}ON{% else %}OFF{% endif %}** because it was consuming less than 30W for 5 minutes"