- alias: dashbutton
  trigger:
    platform: event
    event_type: botodash
  action:
    - service: notify.HomeAssistant
      data:
        message: "dashbutton pressed"
    - service: automation.trigger
      data_template:
        entity_id: >-
          {% if is_state('switch.sonoffTVset', 'on') %}
            automation.TC_TVset_off
          {% else %}
            automation.TC_TVset_on
          {% endif %}