- alias: botodash
  trigger:
    - platform: state
      entity_id: input_boolean.dashbutton
      from: 'off'
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.sonoffwaterheater
    - delay: 00:00:05
    - service: switch.turn_off
      data:
        entity_id:
          - switch.sonoffwaterheater