- alias: ESPHome1 led off pir
  id: esphome1_led_off_pir
  triggers:
    - trigger: state
      entity_id: binary_sensor.esphome1_motion
      to: "off"
  actions:
    - action: light.turn_off
      data:
        entity_id: light.esphome1_light
        transition: 1
