- alias: 'ESPHome6 led off pir'
  id: esphome6_led_off_pir
  triggers:
    - trigger: state
      entity_id: 'binary_sensor.esphome6_motion'
      to: 'off'
  actions:
    - action: light.turn_off
      data:
        entity_id: light.esphome6_light
        transition: 1
