- alias: ESPHome4 led off pir
  id: esphome4_led_off_pir
  triggers:
    - trigger: state
      entity_id: binary_sensor.esphome4_motion
      to: "off"
  actions:
    - action: light.turn_off
      data:
        entity_id: light.esphome4_light
        transition: 1
