- alias: 'ESPHome5 led off pir'
  id: esphome5_led_off_pir
  triggers:
    - trigger: state
      entity_id: 'binary_sensor.esphome5_motion'
      to: 'off'
  actions:
    - action: light.turn_off
      data:
        entity_id: light.esphome5_light
        transition: 1
