- alias: 'ESPHome6 led on pir'
  trigger:
    platform: state
    entity_id: 'binary_sensor.esphome6_motion'
    to: 'on'
  action:       
    - service: light.turn_on
      data:
        entity_id: light.esphome6_light
        brightness: 30
        rgb_color: [255,0,0]
