- alias: 'ESPHome1 Christmas Tree on motion'
  id: esphome1_motion_detected
  initial_state: true
  triggers:
    - trigger: state
      entity_id: 'binary_sensor.esphome1_motion'
      to: 'on'
  actions:
    - action: script.christmas_tree
  mode: restart