- alias: 'ESPHome4 led off pir'
  trigger:
    platform: state
    entity_id: 'binary_sensor.esphome4_motion'
    to: 'off'
  action:       
    - service: light.turn_off
      data:
        entity_id: light.esphome4_light
        transition: 1
