- alias: 'ESPHome5 led on pir'
  id: esphome5_led_on_pir
  triggers:
    - trigger: state
      entity_id: 'binary_sensor.esphome5_motion'
      to: 'on'
  actions:
    - action: light.turn_on
      data:
        entity_id: light.esphome5_light
        brightness: 30
        rgb_color: [255,0,0]
