- alias: 'Actualización Disponible'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.HomeAssistant
    data:
      message: "Ha salido una nueva actualización de Home Assistant"
