- alias: nfc_mesita
  id: nfc_mesita
  initial_state: true
  triggers:
    - trigger: tag
      tag_id: f75015d5-cbc9-4bfe-b31b-0fb45ba98510
  actions:
    - action: telegram_bot.send_message
      data:
        message: "luz pc toggle"
    - action: switch.toggle
      data:
        entity_id:
          - switch.luz_pc