# http://domology.es/tasmotear-sonoff-rf-bridge-y-anadirlo-en-ha/
# En el caso del PIR como no tiene dos códigos RF 
# (Uno para activarse y otro cuando esta en standby) 
# debemos poner un código inventado realizar un automation 
# para que vuelva al estado original a los x segundos, 
# de lo contrario siempre nos daría que hay movimiento en 
# la estancia cuando no lo hubiera:
# Con esto conseguiríamos que el PIR diera aviso de movimiento 
# y que a los x segundos restableciera su estado a no detectado.   
#
# Al final se manda un código OFF inventado al sensor binario
# a los X segundos para simular que lo hace él mismo al apagarse
- alias: mqtt restart PIR_kerui_p831_3_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_kerui_p831_3
      # from: 'off'
      to: 'on'
      for:
        seconds: 3    
  action:
    - service: mqtt.publish
      data:
         topic: tele/sonoffRF433/RESULT
         payload: '{"RfReceived":{"Data":"FF160Aoff"}}'