###############################
# Remote controller 2 (4 buttons)

###############################
# Button D

- alias: Remote2ButtonD
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.remote2_btnd
    to: 'on'
  action:
    - service: notify.homeassistant
      data:
        message: "Remote2 buttonD pressed"