###############################
# Remote controller 2 (4 buttons)

###############################
# Button C

- alias: Remote2ButtonC
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.remote2_btnc
    to: 'on'
  action:
    - service: notify.send_message
      data:
        entity_id: notify.telegram_bot_701350878_327910374
        message: "Remote2 buttonC pressed"