###############################
# Remote controller 2 (4 buttons)

###############################
# Button B

- alias: Remote2ButtonB
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.remote2_btnb
    to: 'on'
  action:
    - action: telegram_bot.send_message
      data_template:
        message: "Remote2 buttonB pressed"
    # - service: automation.trigger
    #   data_template:
    #     entity_id: >-
    #       {% if is_state('switch.sw03_8tree', 'on') %}
    #         automation.TC_computer_off
    #       {% else %}
    #         automation.TC_computer_on
    #       {% endif %}