- alias: Remote1ButtonDon
  id: remote1_buttond_on
  initial_state: true
  triggers:
    - trigger: state
      entity_id: binary_sensor.remote1_btnd
      to: 'on'
  conditions:
    - condition: state
      entity_id: light.yeelight_1
      state: 'off'
  actions:
    - action: light.turn_on
      data:
        entity_id: light.Yeelight_1
        brightness: 10

- alias: Remote1ButtonDstep
  id: remote1_buttond_step
  triggers:
    - trigger: state
      entity_id: binary_sensor.remote1_btnd
      to: 'on'
  conditions:
    - condition: numeric_state
      entity_id: light.yeelight_1
      value_template: '{% if states.light.Yeelight_1.state == "on"  %}{{ states.light.Yeelight_1.attributes.brightness }}{% else %}0{% endif %}'
      below: 220
  actions:
    - action: script.yeelight_step

- alias: Remote1ButtonDoff
  id: remote1_buttond_off
  triggers:
    - trigger: state
      entity_id: binary_sensor.remote1_btnd
      to: 'on'
  conditions:
    - condition: numeric_state
      entity_id: light.yeelight_1
      value_template: '{% if states.light.Yeelight_1.state == "on"  %}{{ states.light.Yeelight_1.attributes.brightness }}{% else %}0{% endif %}'
      above: 230
  actions:
    - action: light.turn_off
      data:
        entity_id: light.Yeelight_1