###############################
# Remote controller 4 buttons

###############################
# Button A

- alias: Remote1ButtonA
  id: remote1_buttona
  initial_state: true
  triggers:
    - trigger: state
      entity_id: binary_sensor.remote1_btna
      to: 'on'
  actions:
    - action: telegram_bot.send_message
      data:
        message: "Remote1 buttonA pressed"
    - if:
        - condition: state
          entity_id: switch.blitzw0lf_6
          state: 'on'
      then:
        - action: telegram_bot.send_message
          data:
            message: "TVset off"
        - action: switch.turn_off
          target:
            entity_id: switch.blitzw0lf_6
      else:
        - action: telegram_bot.send_message
          data:
            message: "TVset on"
        - action: switch.turn_on
          target:
            entity_id: switch.blitzw0lf_6
