###############################
# Remote controller 2 (4 buttons)

###############################
# Button B

- alias: Remote2ButtonB
  id: remote2_buttonb
  initial_state: true
  triggers:
    - trigger: state
      entity_id: binary_sensor.remote2_btnb
      to: 'on'
  actions:
    - action: telegram_bot.send_message
      data:
        message: "Remote2 buttonB pressed"
