- alias: "Power state on HA start-up"
  initial_state: true
  triggers:
    - trigger: homeassistant
      event: start
  actions:
    - action: switch.turn_on
      data:
        entity_id: switch.sonoffbasic_3
    - repeat:
        for_each:
          - binary_sensor.pir_kerui_p831_1
          - binary_sensor.pir_kerui_p831_2
          - binary_sensor.pir_kerui_p831_3
          - binary_sensor.remote1_btna
          - binary_sensor.remote1_btnb
          - binary_sensor.remote1_btnc
          - binary_sensor.remote1_btnd
          - binary_sensor.remote2_btna
          - binary_sensor.remote2_btnb
          - binary_sensor.remote2_btnc
          - binary_sensor.remote2_btnd
        sequence:
          - action: python_script.set_state
            data:
              entity_id: "{{ repeat.item }}"
              state: 'off'
    - action: telegram_bot.send_message
      data:
        message: 'HA has started: Revise status'
    - action: media_player.volume_set
      data:
        entity_id: media_player.speaker
        volume_level: '{{ ((states(''input_number.notification_max_volume'') | float(1))
                * (0.5 if (now().hour >= (states(''input_number.notification_night_start_hour'')
                | int) or now().hour < (states(''input_number.notification_night_end_hour'')
                | int)) else 1)) | round(3) }}'
    - delay: 00:00:01
    - action: tts.google_say
      target:
        entity_id: media_player.speaker
      data:
        message: 'Atención David!. "Home assístant" se ha reiniciado, revísalo.'
        language: 'es'
    - delay: 00:00:10
    - action: switch.turn_off
      data:
        entity_id: switch.sonoffbasic_3
  mode: single
    
    

