- alias: Printig Job finished
  trigger:
      platform: state
      entity_id: binary_sensor.octoprint_printing
      from: 'on'
      to: 'off'
  actions:
    - action: telegram_bot.send_message
      data_template:
        message: '3d printing job just finished, do you want to turn printer off?'
        inline_keyboard: 
          - '✔Yes:/TCB_3dprinter_off, ❌No:/TCB_cancel'