- alias: 'Blitzwolf6 reset'
  initial_state: 'true'
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%d") == "01" }}'
  action:
    - service: script.blitzwolf6_report
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_6/energyreset1"
        payload: "0"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_6/energyreset2"
        payload: "0"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_6/energyreset3"
        payload: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw6_Kw_pico
        value: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw6_Kw_valle
        value: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw6_partial
        value: "0"
      
- alias: 'Blitzwolf6 Valle'
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%M") == "00" }}'
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H") == "13" }}'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw6_kw_valle
        value: "{{ ((states.input_number.bw6_kw_valle.state|float) + ((states.sensor.bw6_total.state|float) - (states.input_number.bw6_partial.state|float))|float) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw6_partial
        value: "{{ states.sensor.bw6_total.state }}"          
#    - service: script.blitzwolf4_report

- alias: 'Blitzwolf6 Pico'
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%M") == "00" }}'
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H") == "23" }}'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw6_kw_pico
        value: "{{ ((states.input_number.bw6_kw_pico.state|float) + ((states.sensor.bw6_total.state|float) - (states.input_number.bw6_partial.state|float))|float) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw6_partial
        value: "{{ states.sensor.bw6_total.state }}"      
#    - service: script.blitzwolf4_report     