- alias: 'Blitzwolf5 reset'
  initial_state: 'true'
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%d") == "01" }}'
  action:
    - service: script.blitzwolf5_report
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_5/energyreset1"
        payload: "0"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_5/energyreset2"
        payload: "0"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_5/energyreset3"
        payload: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw5_Kw_pico
        value: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw5_Kw_valle
        value: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw5_partial
        value: "0"
      
- alias: 'Blitzwolf5 Valle'
  hide_entity: true
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%M") == "00" }}'
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H") == "12" }}'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw5_kw_valle
        value: "{{ ((states.input_number.bw5_kw_valle.state|float) + ((states.sensor.bw5_total.state|float) - (states.input_number.bw5_partial.state|float))|float) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw5_partial
        value: "{{ states.sensor.bw5_total.state }}"

- alias: 'Blitzwolf5 Pico'
  hide_entity: true
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%M") == "00" }}'
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H") == "22" }}'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw5_kw_pico
        value: "{{ ((states.input_number.bw5_kw_pico.state|float) + ((states.sensor.bw5_total.state|float) - (states.input_number.bw5_partial.state|float))|float) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw5_partial
        value: "{{ states.sensor.bw5_total.state }}"