- alias: 'Blitzwolf3 reset'
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%d") == "1" }}'
  action:
    - service: persistent_notification.create
      data_template:
        title: "Blitwolf3 from {{ (states.sensor.bw3_totalstarttime.state) | timestamp_custom('%d/%m/%Y %H:%M:%S' )}} to {{ as_timestamp(now()) | timestamp_custom('%d/%m/%Y %H:%M:%S' )}}"
        message: "Total euros: {{ states.sensor.bw3_total_euro.state_with_unit }} \nTotal KW/h: {{ states.sensor.bw3_total.state_with_unit }}"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_3/energyreset1"
        payload: "0"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_3/energyreset2"
        payload: "0"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_3/energyreset3"
        payload: "0"