- alias: 'Big WC Fan on when light go to off'
  id: sw_basic2_big_wc_fan
  initial_state: true
  triggers:
    - trigger: state
      entity_id: 'switch.luz_bano_grande'
      from: 'on'
      to: 'off'
  conditions:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
  actions:
    - action: switch.turn_on
      data:
        entity_id: switch.ventilador_wc
    - action: timer.start
      data:
        entity_id: timer.timer_sonoff_basic_2
        duration: 00:01:00