##########################################
## 
##
- alias: 'SW_Basic2_Big_WC_timer_ended'
  id: sw_basic2_big_wc_timer_ended
  initial_state: true
  triggers:
    - trigger: event
      event_type: timer.finished
      event_data:
        entity_id: timer.timer_sonoff_basic_2
  actions:
    - action: switch.turn_off
      data:
        entity_id:
          - switch.ventilador_wc