- alias: 'Blitzwolf1 reset'
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%d") == "01" }}'
  action:
    - service: script.blitzwolf1_report
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_1/energyreset1"
        payload: "0"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_1/energyreset2"
        payload: "0"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_1/energyreset3"
        payload: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw1_Kw_pico
        value: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw1_Kw_valle
        value: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw1_partial
        value: "0"
      
- alias: 'Blitzwolf1 Valle'
  hide_entity: true
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%M") == "00" }}'
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H") == "12" }}'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw1_kw_valle
        value: "{{ ((states.input_number.bw1_kw_valle.state|float) + ((states.sensor.bw1_total.state|float) - (states.input_number.bw1_partial.state|float))|float) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw1_partial
        value: "{{ states.sensor.bw1_total.state }}"          
#    - service: script.blitzwolf1_report

- alias: 'Blitzwolf1 Pico'
  hide_entity: true
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%M") == "00" }}'
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H") == "22" }}'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw1_kw_pico
        value: "{{ ((states.input_number.bw1_kw_pico.state|float) + ((states.sensor.bw1_total.state|float) - (states.input_number.bw1_partial.state|float))|float) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw1_partial
        value: "{{ states.sensor.bw1_total.state }}"   
#    - service: script.blitzwolf1_report