- alias: 'Blitzwolf2 reset'
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%d") == "1" }}'
  action:
    - service: script.blitzwolf2_report
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_2/energyreset1"
        payload: "0"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_2/energyreset2"
        payload: "0"
    - service: mqtt.publish
      data_template:
        topic: "cmnd/BliTZW0lF_2/energyreset3"
        payload: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw2_Kw_pico
        value: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw2_Kw_valle
        value: "0"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw2_partial
        value: "0"
      
- alias: 'Blitzwolf2 Valle'
  hide_entity: true
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%M") == "00" }}'
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H") == "12" }}'
  action:
    - service: script.blitzwolf2_report
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw2_kw_valle
        value: "{{ ((states.input_number.bw2_kw_valle.state|float) + ((states.sensor.bw2_total.state|float) - (states.input_number.bw2_partial.state|float))|float) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw2_partial
        value: "{{ states.sensor.bw2_total.state }}"          

- alias: 'Blitzwolf2 Pico'
  hide_entity: true
  initial_state: on
  trigger:
    - platform: template
      value_template: '{{ now().strftime("%M") == "00" }}'
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H") == "22" }}'
  action:
    - service: script.blitzwolf2_report
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw2_kw_pico
        value: "{{ ((states.input_number.bw2_kw_pico.state|float) + ((states.sensor.bw2_total.state|float) - (states.input_number.bw2_partial.state|float))|float) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bw2_partial
        value: "{{ states.sensor.bw2_total.state }}"           