##########################################
## KEYBOARD - 3dprinter_off
##
- alias: 'TC_3dprinter_off'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/3dprinter_off'
  action:
    - service: notify.send_message
      data:
        entity_id: notify.telegram_bot_701350878_327910374
        message: "3dPrinter off"
    - service: switch.turn_off
      data:
        entity_id:
          - switch.BliTZW0lF_2
