##########################################
## KEYBOARD - printer
##
- alias: 'TC 3dprinter'
  initial_state: true
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/3dprinter'
  actions:
    - action: telegram_bot.send_message
      data_template:
        message: 'Select an option'
        keyboard:
          - '/3dprinter_off, /3dprinter_on'
          - '/start'
                