##########################################
## KEYBOARD - 3dprinter_off
##
- alias: 'TC_3dprinter_off'
  id: tc_3dprinter_off
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_command
      event_data:
        command: '/3dprinter_off'
  actions:
    - action: telegram_bot.send_message
      data:
        message: "3dPrinter off"
    - action: switch.turn_off
      data:
        entity_id:
          - switch.BliTZW0lF_2
