##########################################
## KEYBOARD - printer
##
- alias: 'TC 3dprinter'
  initial_state: true
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/3dprinter'
  action:
    - service: notify.send_message
      data:
        entity_id: notify.telegram_bot_701350878_327910374
        message: 'Select an option'
        data:
          keyboard:
          - '/3dprinter_off, /3dprinter_on'
          - '/start'
                