##########################################
## KEYBOARD - 3dprinter_off
##
- alias: 'TC_3dprinter_off'
  initial_state: 'true'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/3dprinter_off'
  action:
    - service: notify.homeassistant
      data:
        message: "3dPrinter off"
    - service: switch.turn_off
      data:
        entity_id:
          - switch.BliTZW0lF_2
