##########################################
## KEYBOARD - computer_on
##
- alias: 'TC_computer_on'
  id: tc_computer_on
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_command
      event_data:
        command: '/computer_on'
  actions:
    - action: telegram_bot.send_message
      data:
        message: "computer on"
    - action: switch.turn_on
      data:
        entity_id:
          - switch.sw03_8tree
