##########################################
## KEYBOARD - computer_off
##
- alias: 'TC_computer_off'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/computer_off'
  action:
    - service: notify.HomeAssistant
      data:
        message: "computer off"
    - service: switch.turn_off
      data:
        entity_id:
          - switch.BliTZW0lF_2
