##########################################
## KEYBOARD - computer
##
- alias: 'TC computer'
  initial_state: 'true'
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/computer'
  action:
     - service: notify.homeassistant
       data:
         message: "Select an option\nComputer is *** {{states.switch.blitzw0lf_3.state.upper()}} ***"
         data:
             keyboard:
               - '/computer_off, /computer_on'
               - '/start'
                