##########################################
## KEYBOARD - computer
##
- alias: 'TC computer'
  initial_state: true
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/computer'
  action:
    - service: notify.send_message
      data:
        entity_id: notify.telegram_bot_701350878_327910374
        message: "Select an option\nComputer is *** {{states.switch.blitzw0lf_3.state.upper()}} ***"
        data:
            keyboard:
              - '/computer_off, /computer_on'
              - '/start'
                