##########################################
## KEYBOARD - computer_on
##
- alias: 'TC_computer_on'
  initial_state: 'true'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/computer_on'
  action:
    - service: notify.homeassistant
      data:
        message: "computer on"
    - service: switch.turn_on
      data:
        entity_id:
          - switch.BliTZW0lF_3
