##########################################
## KEYBOARD - light_PC
##
- alias: 'TC light PC'
  initial_state: true
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/light_pc'
  actions:
    - action: telegram_bot.send_message
      data_template:
        message: 'Select an option'
        keyboard:
        - '/light_pc_off, /light_pc_on'
        - '/start'