##########################################
## KEYBOARD - light_pc_off
##
- alias: 'TC_light_pc_off'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/light_pc_off'
  action:
    - service: notify.homeassistant
      data:
        message: "light pc off"
    - service: switch.turn_off
      data:
        entity_id:
          - switch.luz_pc
