##########################################
## KEYBOARD - light_pc_off
##
- alias: 'TC_light_pc_off'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/light_pc_off'
  actions:
    - action: telegram_bot.send_message
      data_template:
        message: "light pc off"
    - action: switch.turn_off
      data:
        entity_id:
          - switch.luz_pc
