##########################################
## KEYBOARD - Printer_off
##
- alias: 'TC_Printer_off'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/Printer_off'
  action:
    - service: notify.HomeAssistant
      data:
        message: "Printer off"
    - service: switch.turn_off
      data:
        entity_id:
          - switch.sonoffPrinter
