##########################################
## KEYBOARD - Printer_on
##
- alias: 'TC_Printer_on'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/Printer_on'
  action:
    - service: notify.HomeAssistant
      data:
        message: "Printer on"
    - service: switch.turn_on
      data:
        entity_id:
          - switch.sonoffPrinter