#
##########################################
## KEYBOARD - ping
##
- alias: 'TC ping'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    - service: notify.HomeAssistant
      data:
        message: "pong"
