##########################################
## KEYBOARD - Printer_on
##
- alias: 'TC_Printer_on'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/Printer_on'
  actions:
    - action: telegram_bot.send_message
      data_template:
        message: "Printer on"
    - action: switch.turn_on
      data:
        entity_id:
          - switch.sonoffPrinter