##########################################
## KEYBOARD - Printer
##
- alias: 'TC Printer'
  initial_state: 'true'
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/Printer'
  action:
     - service: notify.homeassistant
       data:
         message: 'Select an option'
         data:
            keyboard:
            - '/Printer_on, /Printer_off'
            - '/start'
                