#
##########################################
## KEYBOARD - ping
##
- alias: 'TC ping'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    - action: telegram_bot.send_message
      data_template:
        message: "pong"
