##########################################
## KEYBOARD - start
##
- alias: 'TC start'
  hide_entity: true
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/start'
  action:
     - service: notify.HomeAssistant
       data:
         message: 'Tria una opció'
         data:
            keyboard:
                - '/status, /ping, /avanzado'
                - '/automation, /remoto'
                - '/alarma, /puertas, /switches'