##########################################
## KEYBOARD - start
##
- alias: 'TC start'
  initial_state: 'true'
  hide_entity: false
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/start'
  action:
     - service: notify.homeassistant
       data:
         message: 'Select an option'
         data:
            keyboard:
                - '/status, /gas95, /ping'
                - '/waterheater, /TVset' 
                #, /Printer'
                - '/computer, /3dprinter, /shutter'
                #- '/alarma, /puertas, /switches'