##########################################
## KEYBOARD - start
##
- alias: 'TC start'
  hide_entity: true
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/start'
  action:
     - service: notify.HomeAssistant
       data:
         message: 'Select an option'
         data:
            keyboard:
                - '/status, /ping'
                - '/waterheater, /TVset' 
                #, /Printer'
                - '/computer'
                #- '/alarma, /puertas, /switches'