##########################################
## KEYBOARD - status
##
- alias: 'TC status'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/status'
  action:
    - service: notify.HomeAssistant
      data_template:
          title: "***Sensors:***"
          message: "{% for state in states.sensor -%}
          {%- if loop.first %}  - {% elif loop.last %} \n - {% else %}\n - {% endif -%}
            {{ state.name | lower }}: ***{{state.state_with_unit}}***
          {%- endfor %}"