##########################################
## KEYBOARD - switches
##
- alias: 'TC switches'
  initial_state: true
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/computer'
  actions:
    - action: telegram_bot.send_message
      data_template:
        message: 'Select an option'
        data:
          keyboard:
          - '/computer_off, /computer_on'
          - '/start'
                