##########################################
## KEYBOARD - start
##
- alias: 'TC start'
  initial_state: true
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/start'
  action:
    - service: notify.send_message
      data:
        entity_id: notify.telegram_bot_701350878_327910374
        message: 'Select an option'
        data:
          keyboard:
            - '/status, /gas95, /ping'
            - '/lights'
            - '/waterheater, /TVset' 
            #, /Printer'
            - '/computer, /3dprinter, /shutter'
            #- '/alarma, /puertas, /switches'