##########################################
## KEYBOARD - shutter
##
- alias: 'TC shutter'
  id: tc_shutter
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_command
      event_data:
        command: '/shutter'
  actions:
    - action: telegram_bot.send_message
      data:
        message: "Select an option\nShutter is in position *** {{states.input_number.window_position.state}} of 28***"
        keyboard:
          - '/shutter_close, /shutter_open'
          - '/shutter_bit_open, /shutter_half'
          - '/shutter_stop'
          - '/start'