##########################################
## KEYBOARD - shutter close
##
- alias: 'TC_shutter_close'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/shutter_close'
  actions:
    - action: telegram_bot.send_message
      data_template:
        message: "close shutters"
    - action: input_number.set_value
      data_template:
        entity_id: input_number.window_set_position
        value: 1
    - delay: 00:00:01
    - action: input_number.set_value
      data_template:
        entity_id: input_number.window_set_position
        value: 0
    - delay: 00:00:30
    - action: telegram_bot.send_message
      data_template:
        message: 
          "Shutter is in position Shutter is in position ***{{states.input_number.window_position.state}} of 28***"                         