##########################################
## KEYBOARD - TVset
##
- alias: 'TC TVset'
  initial_state: 'true'
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/TVset'
  action:
     - service: notify.homeassistant
       data:
         message: 'Select an option'
         data:
            keyboard:
            - '/TVset_on, /TVset_off'
            - '/start'
                