##########################################
## KEYBOARD - TVset_off
##
- alias: 'TC_TVset_off'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/TVset_off'
  action:
    - service: notify.send_message
      data:
        entity_id: notify.telegram_bot_701350878_327910374
        message: "TVset off"
    - service: switch.turn_off
      data:
        entity_id:
          - switch.blitzw0lf_6
