##########################################
## KEYBOARD - TVset_on
##
- alias: 'TC_TVset_on'
  id: tc_tvset_on
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_command
      event_data:
        command: '/TVset_on'
  actions:
    - action: telegram_bot.send_message
      data:
        message: "TVset on"
    - action: switch.turn_on
      data:
        entity_id:
          - switch.blitzw0lf_6
