##########################################
## KEYBOARD - TVset_off
##
- alias: 'TC_TVset_off'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/TVset_off'
  action:
    - service: notify.HomeAssistant
      data:
        message: "TVset off"
    - service: switch.turn_off
      data:
        entity_id:
          - switch.sonoffTVset
