##########################################
## KEYBOARD - TVset_on
##
- alias: 'TC_TVset_on'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/TVset_on'
  action:
    - service: notify.HomeAssistant
      data:
        message: "TVset on"
    - service: switch.turn_on
      data:
        entity_id:
          - switch.sonoffTVset
