##########################################
## KEYBOARD - TVset_off
##
- alias: 'TC_TVset_off'
  id: tc_tvset_off
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_command
      event_data:
        command: '/TVset_off'
  actions:
    - action: telegram_bot.send_message
      data:
        message: "TVset off"
    - action: switch.turn_off
      data:
        entity_id:
          - switch.blitzw0lf_6
