##########################################
## KEYBOARD - TVset_on
##
- alias: 'TC_TVset_on'
  initial_state: 'true'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/TVset_on'
  action:
    - service: notify.homeassistant
      data:
        message: "TVset on"
    - service: switch.turn_on
      data:
        entity_id:
          - switch.sonoffTVset
