##########################################
## KEYBOARD - TVset
##
- alias: 'TC TVset'
  id: tc_tvset
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_command
      event_data:
        command: '/TVset'
  actions:
    - action: telegram_bot.send_message
      data:
        message: 'Select an option'
        keyboard:
        - '/TVset_on, /TVset_off'
        - '/start'
                