##########################################
## KEYBOARD - waterheater_15min
##
- alias: 'TC waterheater_15min'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/waterheater_15min'
  action:
    - service: notify.HomeAssistant
      data:
        message: "waterheater on for 15 minutes - start"  
    - service: switch.turn_on
      data:
        entity_id:
          - switch.BliTZW0lF_1
    - delay: "00:15:00"
    - service: switch.turn_off
      data:
        entity_id:
          - switch.BliTZW0lF_1          
    - service: notify.HomeAssistant
      data:
        message: "waterheater on for 15 minutes - end"