##########################################
## KEYBOARD - waterheater
##
- alias: 'TC waterheater'
  id: tc_waterheater
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_command
      event_data:
        command: '/waterheater'
  actions:
    - action: telegram_bot.send_message
      data:
        message: 'Select an option'
        keyboard:
          - '/waterheater_60min, /waterheater_30min, /waterheater_15min'
          - '/waterheater_off, /waterheater_on'
          - '/start'
                