##########################################
## KEYBOARD - waterheater_60min
##
- alias: 'TC waterheater_60min'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/waterheater_60min'
  action:
    - service: notify.send_message
      data:
        entity_id: notify.telegram_bot_701350878_327910374
        message: "waterheater on for 60 minutes - start"  
    - service: switch.turn_on
      data:
        entity_id:
          - switch.BliTZW0lF_1
    - delay: "01:00:00"
    - service: switch.turn_off
      data:
        entity_id:
          - switch.BliTZW0lF_1
    - service: notify.send_message
      data:
        entity_id: notify.telegram_bot_701350878_327910374
        message: "waterheater on for 60 minutes - end"