##########################################
## KEYBOARD - waterheater
##
- alias: 'TC waterheater'
  hide_entity: true
  trigger:
     - platform: event
       event_type: telegram_command
       event_data:
         command: '/waterheater'
  action:
     - service: notify.HomeAssistant
       data:
         message: 'Select an option'
         data:
            keyboard:
            - '/waterheater_30min, /waterheater_15min'
            - '/waterheater_off, /waterheater_on'
            - '/start'
                