##########################################
## KEYBOARD - waterheater_on
##
- alias: 'TC_waterheater_on'
  initial_state: 'true'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/waterheater_on'
  action:
    - service: notify.homeassistant
      data:
        message: "waterheater on"
    - service: switch.turn_on
      data:
        entity_id:
          - switch.BliTZW0lF_1
