##########################################
## INLINE_KEYBOARD - TBC_computer_on
##
- alias: 'TCB_computer_on'
  initial_state: 'true'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_computer_on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.BliTZW0lF_3
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Starting computer'    
    - service: telegram_bot.delete_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
    - delay: 00:00:01    
    - service: notify.homeassistant
      data:
        message: 
          "Computer started after arriving home\nComputer is **{% if is_state('switch.BliTZW0lF_3', 'on') %}ON{% else %}OFF{% endif %}**"