##########################################
## INLINE_KEYBOARD - TBC_speaker_off
##
- alias: 'TCB_speaker_off'
  initial_state: 'true'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_speaker_off'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.sonoffbasic_3
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Powering off speaker'
    - service: telegram_bot.delete_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
    - service: media_player.media_stop
      data:
        entity_id: media_player.speaker
    - delay: 00:00:01    
    - service: notify.homeassistant
      data:
        message: 
          "Speaker turned off after Good Morning script\nSpeaker is **{% if is_state('switch.sonoffbasic_3', 'on') %}ON{% else %}OFF{% endif %}**"