##########################################
## INLINE_KEYBOARD - TBC_computer_on
##
- alias: 'TCB_computer_on'
  id: tcb_computer_on
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_computer_on'
  actions:
    - action: switch.turn_on
      data:
        entity_id:
          - switch.sw03_8tree
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Starting computer'
    - action: telegram_bot.delete_message
      data:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
    - delay: 00:00:01
    - action: telegram_bot.send_message
      data:
        message:
          "Computer started after arriving home\nComputer is **{% if is_state('switch.sw03_8tree', 'on') %}ON{% else %}OFF{% endif %}**"