##########################################
## INLINE_KEYBOARD - TBC_computer_on
##
- alias: 'TCB_3dprinter_off'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_3dprinter_off'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.BliTZW0lF_2
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Powering down 3d printer'    
    - service: telegram_bot.delete_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
    - service: notify.homeassistant
      data:
        message: "3d printer powered down after printing job"
#    - service: telegram_bot.edit_message
#      data_template:
#        message_id: '{{ trigger.event.data.message.message_id }}'
#        chat_id: '{{ trigger.event.data.chat_id }}'
#        title: '*Message edit*'
#        inline_keyboard:
#          - "Edit message:/edit_msg, Don't:/do_nothing"
#          - "Remove this button:/remove button"
#        message: >
#          Callback received from {{ trigger.event.data.from_first }}.
#          Message id: {{ trigger.event.data.message.message_id }}.
#          Data: {{ trigger.event.data.data }}   
