##########################################
## INLINE_KEYBOARD - TCB_cancel
##
- alias: 'TCB_cancel'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_cancel'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Nothing to do'
        show_alert: false
    - service: telegram_bot.delete_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
    - service: notify.send_message
      data:
        entity_id: notify.telegram_bot_701350878_327910374
        message: "You've answered not, maybe next time. Bye."        
#    - service: telegram_bot.edit_replymarkup
#      data_template:
#        message_id: '{{ trigger.event.data.message.message_id }}'
#        chat_id: '{{ trigger.event.data.chat_id }}'
#        inline_keyboard:
#          - 'Yes:/TCB_computer_on, No:/TCB_cancel'
#          - "Remove this button:/remove button"