- alias: 'Front door open'
  id: front_door_open
  initial_state: true
  triggers:
    - trigger: state
      entity_id: 'binary_sensor.front_door'
      to: 'on'
#  condition:
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: device_tracker.
#        state: 'home'
#      - condition: state
#        entity_id: device_tracker.
#        state: 'home'
  actions:
    - action: telegram_bot.send_message
      data:
        chat_id: !secret id_group_telegram
        message: 'Front door opened'
