- alias: 'Front close open'
  initial_state: true
  trigger:
    platform: state
    entity_id: 'binary_sensor.front_door'
    to: 'off'
#  condition:
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: device_tracker.
#        state: 'home'
#      - condition: state
#        entity_id: device_tracker.
#        state: 'home'
  action:
    - service: telegram_bot.send_message
      data_template:
        chat_id: !secret id_group_telegram
        message: "Front door closed"
