- alias: 'Front door open for 5 minutes'
  id: front_door_leaved_open
  initial_state: true
  triggers:
    - trigger: state
      entity_id: 'binary_sensor.front_door'
      # from: 'off'
      to: 'on'
      for:
        minutes: 1
    - trigger: state
      entity_id: 'binary_sensor.front_door'
      # from: 'off'
      to: 'on'
      for:
        minutes: 5
    - trigger: state
      entity_id: 'binary_sensor.front_door'
      # from: 'off'
      to: 'on'
      for:
        minutes: 10
    - trigger: state
      entity_id: 'binary_sensor.front_door'
      # from: 'off'
      to: 'on'
      for:
        minutes: 15
    - trigger: state
      entity_id: 'binary_sensor.front_door'
      # from: 'off'
      to: 'on'
      for:
        minutes: 20
  actions:
    - action: telegram_bot.send_message
      data:
        message: "Front door Still Open!!!"
