- alias: 'Front close open'
  initial_state: true
  trigger:
    platform: state
    entity_id: 'binary_sensor.front_door'
    to: 'off'
#  condition:
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: device_tracker.
#        state: 'home'
#      - condition: state
#        entity_id: device_tracker.
#        state: 'home'
  action:
    - service: notify.homeassistant
      data:
        message: "Front door closed"
