- alias: 'PIR motion 1 nothome'
  initial_state: 'true'
  #hide_entity: true
  trigger:
    platform: state
    entity_id: 'binary_sensor.PIR_kerui_p831_1'
    to: 'on'
  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: device_tracker.
#        state: 'not_home'
      - condition: state
        entity_id: device_tracker.dmp8p
        state: 'not_home'
  action:
    service: notify.homeassistant
    data:
      message: "PIR motion 1 nothome"