- alias: 'PIR motion 1_day'
  hide_entity: true
  trigger:
    platform: state
    entity_id: 'binary_sensor.PIR_kerui_p831_1'
    to: 'on'
    
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: above_horizon
      - condition: numeric_state
        entity_id: sensor.lolin3_ldr
        below: 25
  action:
    #- service: notify.HomeAssistant
    #  data:
    #    message: "PIR motion 1 day"
    - service: script.yeelight_day
