- alias: 'PIR motion 1 nothome'
  #hide_entity: true
  trigger:
    platform: state
    entity_id: 'binary_sensor.PIR_kerui_p831_1'
    to: 'on'
  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: device_tracker.onepluslan_5gh
#        state: 'not_home'
      - condition: state
        entity_id: device_tracker.oneplus
        state: 'not_home'
  action:
    service: notify.HomeAssistant
    data:
      message: "PIR motion 1 nothome"