- alias: 'PIR motion 1 nothome'
  initial_state: true
  trigger:
    platform: state
    entity_id: 'binary_sensor.pir_kerui_p831_1'
    to: 'on'
  condition:
   condition: or
   conditions:
     - condition: state
       entity_id: device_tracker.rdm13nppmovil
       state: 'not_home'
     - condition: state
       entity_id: device_tracker.rdm13nppmovil
       state: 'unavailable'
  actions:
    - action: telegram_bot.send_message
      data_template:
        message: "PIR motion 1 nothome"