- alias: 'PIR motion 1_night'
  initial_state: true
  trigger:
    platform: state
    entity_id: 'binary_sensor.pir_kerui_p831_1'
    to: 'on'
  condition: 
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:   
    #- service: notify.homeassistant
    #  data:
    #    message: "PIR motion 1 night"
    - service: script.yeelight_night
