- alias: 'Sunset'
  id: sunset
  initial_state: true
  triggers:
    - trigger: sun
      event: sunset
      #offset: "-00:45:00"
  #condition:
    #condition: state
    #entity_id: group.all_devices
    #state: home
  actions:
    - action: telegram_bot.send_message
      data:
        message: "Sunset"