- alias: 'Sunset'
  initial_state: 'true'
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    #offset: "-00:45:00"
  #condition:
    #condition: state
    #entity_id: group.all_devices
    #state: home
  action:
    service: notify.homeassistant
    data:
      message: "Sunset"