- alias: 'Sunset'
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    #offset: "-00:45:00"
  #condition:
    #condition: state
    #entity_id: group.all_devices
    #state: home
  actions:
    - action: telegram_bot.send_message
      data_template:
        message: "Sunset"