- alias: 'UpdateAvailable'
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    service: notify.homeassistant
    data:
      message: "La nueva versión {{ state_attr('binary_sensor.updater', 'newest_version') }} de Home Assistant está disponible\n Release notes: {{ state_attr('binary_sensor.updater', 'release_notes') }}"
