##########################################
## INLINE_KEYBOARD - TCB_notifications_refresh
##
- alias: 'TCB_notifications_refresh'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_notifications_refresh'
  action:
    - delay: 00:00:01
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Refresh Notifications menu'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_notifications_menu_buttons.btn