camera:
  - platform: ffmpeg
    name: yi2
    input: -rtsp_transport tcp -i rtsp://yi2.casa/ch0_1.h264
binary_sensor:
  - platform: mqtt
    state_topic: "yicam2/motion"
    name: "yicam2_motion_sensor"
    payload_on: "motion_start"
    payload_off: "motion_stop"
    device_class: motion