##########################################
## INLINE_KEYBOARD - TCB_waterheater_timerstopped
##
- alias: 'TCB_waterheater_timerstopped'
  initial_state: 'true'
  trigger:
  - event_data:
      entity_id: timer.waterheater
    event_type: timer.finished
    platform: event
  condition: []
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.BliTZW0lF_1      
    - delay: 00:00:01
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'WaterHeater timer ended'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_waterheater_menu_buttons.btn