##########################################
## INLINE_KEYBOARD - TCB_sensors_frontdoor_off
##
- alias: 'TCB_sensors_frontdoor_off'
  id: tcb_sensors_frontdoor_off
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_sensors_frontdoor_off'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Switching Sensor front door off'
    - action: python_script.set_state
      data:
        entity_id: binary_sensor.front_door
        state: 'off'
    - delay: 00:00:01
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_sensors_menu_buttons.btn