##########################################
## INLINE_KEYBOARD - TCB_sensors_refresh
##
- alias: 'TCB_sensors_refresh'
  id: tcb_sensors_refresh
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_sensors_refresh'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Refresh sensors menu'
    - delay: 00:00:01
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_sensors_menu_buttons.btn