##########################################
## INLINE_KEYBOARD - TCB_gasolina_menu
##
- alias: 'TCB_gasolina_menu'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/TCB_gasolina_menu'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Gasolina menu selected'
    - service: telegram_bot.edit_message
      data_template:
        message_id: 'last' 
#{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        disable_web_page_preview: yes
        message: >-
            {{"\U000026fd ***Gasolina 95*** \U000026fd\n"}}
            {{"\n***Carlet*** (" + states.sensor.gasolinera1.attributes.Fecha + ")\n"}}{% for entity_id in states.group.gasolinerascarlet.attributes.entity_id %}{% set domain, device = entity_id.split('.') %}{{"- `" + states[domain][device].state + "` ___(" + states[domain][device].name + ")___ [\U0001f4cd](https://www.google.com/maps/dir/?api=1&origin=Current+Location&destination=" + states[domain][device].attributes.latitude + "," + states[domain][device].attributes.longitude + ")\n"}}{% endfor %}
            {{"\n***Catadau*** (" + states.sensor.gasolinera2.attributes.Fecha + ")\n"}}{% for entity_id in states.group.gasolinerascatadau.attributes.entity_id %}{% set domain, device = entity_id.split('.') %}{{"- `" + states[domain][device].state + "` ___(" + states[domain][device].name + ")___ [\U0001f4cd](https://www.google.com/maps/dir/?api=1&origin=Current+Location&destination=" + states[domain][device].attributes.latitude + "," + states[domain][device].attributes.longitude + ")\n"}}{% endfor %}
            {{"\n***Alcudia*** (" + states.sensor.gasolinera3.attributes.Fecha + ")\n"}}{% for entity_id in states.group.gasolinerasalcudia.attributes.entity_id %}{% set domain, device = entity_id.split('.') %}{{"- `" + states[domain][device].state + "` ___(" + states[domain][device].name + ")___ [\U0001f4cd](https://www.google.com/maps/dir/?api=1&origin=Current+Location&destination=" + states[domain][device].attributes.latitude + "," + states[domain][device].attributes.longitude + ")\n"}}{% endfor %}        
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_gasolina_menu_buttons.btn
