##########################################
## INLINE_KEYBOARD - TCB_gasolina_menu
##
- alias: 'TCB_gasolina_menu'
  id: tcb_gasolina_menu
  initial_state: true
  triggers:
    - trigger: event
      event_type: telegram_callback
      event_data:
        data: '/TCB_gasolina_menu'
  actions:
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Gasolina menu selected'
    - action: telegram_bot.edit_message
      data:
        message_id: 'last'
#{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        disable_web_page_preview: yes
        message: !include TCB_gasolina_menu_message.msg
    - action: telegram_bot.edit_replymarkup
      data:
        message_id: 'last'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: !include TCB_gasolina_menu_buttons.btn
